### ISSUE TITLE
Is there a way to use pouchdb-find when directly accessing couchDB, through pouchDB instance.

### ISSUE THREAD

**Issue by havocdrake** [nolanlawson/pouchdb-find#102]
<pre>
var db = new PouchDB('http://admin:admin@localhost:5984/product');
db.find({
      selector: {
             barcode : barcode,
       }
}).then(function(response){ /*...*/ });
</pre>

**Comment by garrensmith** [comment]
Yes it works with CouchDB. Just set the PouchDB database url to point to a CouchDB instance and use the PouchDB-find functionality. 

All misspelling thanks to my iPhone

**Comment by garrensmith** [comment]
Closing this since its not an issue.

**Comment by havocdrake** [comment]
Its not working for me, it always returns:
<pre>
Remote Address:127.0.0.1:5984
Request URL:http://localhost:5985/monthly_totals/_find
Request Method:POST
Status Code:400 Bad Request
</pre>

**Comment by nolanlawson** [comment]
@havocdrake This plugin only works for CouchDB 2.0+, not CouchDB 1.x.
