### ISSUE TITLE
not work in node.js

### ISSUE THREAD

**Issue by c941010623** [nolanlawson/pouchdb-find#103]
i have couchdb 1.6.1 and i install pouchdb in my nodejs
use code:

var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-find'));
var db = new PouchDB('http://localhost:5984/testdb');

db.find({
    selector: {
        name: 'Mario'
    },
    fields: ['_id', 'name'],
    sort: ['name']
}).then(function (result) {
    console.log(result)
}).catch(function (err) {
    console.log(err)
});

any ans...

{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }

why ???
how can i do ?

**Comment by garrensmith** [comment]
What version of Node and PouchDB and PouchDB-find?

All misspelling thanks to my iPhone

**Comment by c941010623** [comment]
i only use npm install pouchdb-find and npm install pouchdb
couchdb is 1.6.1

and not use db.find to couchdb ....
but  node.js local is work   
why ??

**Comment by garrensmith** [comment]
CouchDB 1.6 doesn't support query. You need to use CouchDB from the master branch or PouchDB-server

All misspelling thanks to my iPhone
