### ISSUE TITLE
$all operator not working as expected

### ISSUE THREAD

**Issue by fariasf** [nolanlawson/pouchdb-find#104]
My db has documents with tags, an array of strings, like this:
```
{
  "description": "Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit.",
  "tags": ["tag1", "tag2"]
}
```

From MongoDB docs (I haven't found the docs for Mango/pouchdb-find):
> The $all operator selects the documents where the value of a field is an array that contains all the specified elements.

So I'm trying to use the `$all` operator to find the docs containing all the tags in my query, but `find` always returns the full list of documents (even those with `tags = []`).

I created http://codepen.io/ffarias/pen/VvBXeq to reproduce (use the buttons and check the results in the console).

**Comment by garrensmith** [comment]
You have to combine the $all operator with another operator. Like the [Cloudant Docs mention](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```
