### ISSUE TITLE
Is there a way to use pouchdb-find when directly accessing couchDB, through pouchDB instance(issue: recreated)

### ISSUE THREAD

**Issue by havocdrake** [nolanlawson/pouchdb-find#105]
Its not working for me, it always returns:
Using couchDB 1.6.1, pouchDB 3.6.0, pouchdb-find 0.6.0

<pre>
<b>JS Code:</b>
var db = new PouchDB('http://admin:admin@localhost:5984/product');
db.find({
      selector: {
             barcode : barcode,
       }
}).then(function(response){ /*...*/ });

<b>Request returns: </b>
Remote Address:127.0.0.1:5984
Request URL:http://localhost:5984/product/_find
Request Method:POST
Status Code:400 Bad Request
</pre>

**Comment by garrensmith** [comment]
CouchDB 1.6 doesn't support PouchDB-find. You need to use PouchDB-server, Cloudant or CouchDB master. 

All misspelling thanks to my iPhone
