### ISSUE TITLE
Max of 200 documents when querying Cloudant

### ISSUE THREAD

**Issue by arnoutaertgeerts** [nolanlawson/pouchdb-find#106]
Is it possible I get a maximum of 200 documents when querying a Cloudant database? I'm using pouchdb as a client to the Cloudant database.

**Comment by garrensmith** [comment]
I don't really understand your question. But you can use limit to limit the number of documents retrieved. 

All misspelling thanks to my iPhone

**Comment by arnoutaertgeerts** [comment]
When I use the plugin to query my Cloudant database the maximum amount of docs that are returned is 200 although I did not specify a limit. I'm expecting a lot more documents :)

**Comment by garrensmith** [comment]
You need to test and see if when using curl or the cloudant dadhboard if you get the same number of docs or more. 

All misspelling thanks to my iPhone

**Comment by arnoutaertgeerts** [comment]
When I execute the exact same query in the cloudant dashboard I get all the documents (so > 200). I tested this for several different databases.

**Comment by garrensmith** [comment]
Can you share your query syntax. 

All misspelling thanks to my iPhone

**Comment by arnoutaertgeerts** [comment]
```{
        "selector": {
          "offtake": {
            "$exists": true
          }
        },
        "fields": [
          "_id",
          "offtake"
        ]
      }```

**Comment by garrensmith** [comment]
If I do something like this

``` js
db.find({
   "selector": {
    "_id": {
      "$gt": 0
    },
    "myfield": {
      "$exists": true
    }
  },
  "fields": [
    "_id",
    "_rev"
  ],
  "sort": [
    {
      "_id": "asc"
    }
  ]
})

```

With a Cloudant database I get more than 200 documents. Using just $exists shouldn't work with Cloudant as you need to provide another field to query off. As the [docs say:](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```
