### ISSUE TITLE
$regex not working for me

### ISSUE THREAD

**Issue by henksmeba** [nolanlawson/pouchdb-find#107]
```javascript
db.find({
  selector: {_id: {$regex: /a/}},
  sort: ['_id']
});
```
this will return all documents. I would expect it would return only documents with an a in the _id. Or am i doing something wrong here?

**Comment by henksmeba** [comment]
I now see that the js files in the dist directory don't contain the $regex implementation. Do i need to build these files myself or did something went wrong with publishing the release?

**Comment by garrensmith** [comment]
Sorry you cannot build a query like that. As mentioned in the [cloudant docs](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```
