### ISSUE TITLE
$in not working for me

### ISSUE THREAD

**Issue by vcyang** [nolanlawson/pouchdb-find#108]
It seems that the "$in" will return all docs.  I tested it in the Live Demo (http://nolanlawson.github.io/pouchdb-find/), the same err occurred.

eg.  I replaced  

    db.find({
        selector: {debut: {$gte: 1990}}
     });

with   

    db.find({
        selector: {debut: {$in: [1990, 1991, 1981]}}
    });

 ( in Live Demo,  "Debut >= 1990")
  
but it turned out to be wrong. Am I doing something wrong ? 

Thanks

**Comment by devicezero** [comment]
After playing around with it, it seems to me that $in returns only all docs if it is the only selector. Maybe you can use another selector as a workaround.

E.g. I have a scenario, where I want to filter my docs by **country** (array of one or more country codes) and **price**.

This works and returns 6 docs.
```javascript
db.find({
  selector: {
      price: {$gte: 0},
      country: {$in: ["CR"]}
  },
  fields: ['_id', 'name', 'country']
}).then(function(result) {
  console.log(result);
}).catch(function(err) {
  console.log(err);
});
```

While this returns all of my 171 docs:
```javascript
db.find({
  selector: {
      country: {$in: ["CR"]}
  },
  fields: ['_id', 'name', 'country']
}).then(function(result) {
  console.log(result);
}).catch(function(err) {
  console.log(err);
});
```

**Comment by garrensmith** [comment]
You have to use another operator with `$in`. As the [Cloudant Docs say](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```

**Comment by vcyang** [comment]
@devicezero Thanks for your answer. Since my data to be stored is different: 
```javascript
[{
   productName: "aaa", 
   productId: 12567,
   data: {...}
}, {
   productName: "bbb", 
   productId: 23764,
   data: {...}
},
   ...]
```
Which means that the "productName" (the "_id" as well) should be **String**, and the "productId" is a random **Number**. How I can get objects that **productId $in [12567, 23764]** ?
As suggested by @garrensmith , the [Cloudant Docs](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions) tells me to do this: 
```javascript
            db.find({
                selector: {
                    _id: {$gt: null},
                    productId: {$in: [12567, 23764]}
                }
            });
```
but it return empty docs.
What can I do?

**Comment by garrensmith** [comment]
@vcyang does each document have this structure:

```
{
   _id: 'some-id',   
produceName: 'aaa',
   productId: 12567,
   data: ....
}

```
If it looks like that? Then it should work? Otherwise its a bug.
If that

**Comment by garrensmith** [comment]
Also make sure you using the latest `pouchdb-find` from npm or the dist folder. It is newer than the version on the github page.

**Comment by vcyang** [comment]
@garrensmith Yes, the document structure is like that, but it doesn't work. Could you tell me where I can get the latest version of  `pouchdb-find` ?  I googled it but not found. The current one I using is `0.7.0`.

**Comment by garrensmith** [comment]
That is the latest one. I will try and take a look this week and see if its
a bug.

**Comment by vcyang** [comment]
@garrensmith It works! The reason I fail is that the old data (some properties are missing) have not been deleted before I put new ones in and I haven't noticed that.  :cry::cry::cry::cry:
Thanks a lot!

**Comment by garrensmith** [comment]
Great to hear. Could you close the PR

All misspelling thanks to my iPhone
