### ISSUE TITLE
How to sort by _id?

### ISSUE THREAD

**Issue by yssource** [nolanlawson/pouchdb-find#110]
HI, My _id looks like this
"1", "2", "3" ... "9", "10", "11", "12" ... 
If I try to sort by _id, but it always get such a result,
"1", "10", "11", "12" ... "2", "3", "4" ...
However, This is not what I want.

And, I know _id should only be string type in pouchdb.
Any help?

**Comment by garrensmith** [comment]
@yssource this is working as expected for javascript and strings. If you do `["2","1", "10"].sort();` you will get the same result.

**Comment by angelxmoreno** [comment]
@yssource if you care about order then add a field ( something like `seq`) and have its value be integers, not strings
