### ISSUE TITLE
queries with $size:length are ignored.

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#111]
I have docs with key ``tags`` which is an array.

When performing the following query, I end up getting all tags instead of only the ones with length 0.

```      
var query = {
        selector: {
          tags: {
            $size: 0
          }
        },
        fields: ["tags"]
 };
```

Am I doing anything wrong?

<img width="554" alt="screen shot 2015-11-15 at 4 04 10 pm" src="https://cloud.githubusercontent.com/assets/802819/11171017/90138bba-8bb2-11e5-960b-7f0af3781b83.png">

**Comment by garrensmith** [comment]
Could you try something like.

```js
var query = {
        selector: {
         _id: {$gt: null},
          tags: {
            $size: 0
          }
        },
        fields: ["tags"]
 };
```

**Comment by yattias** [comment]
That seems to work. Also, I have noticed that without the ``_id`` key, most operators are not respected. Thank you.

**Comment by garrensmith** [comment]
This might help, from the [Cloudant Docs](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions):

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```
