### ISSUE TITLE
Is it possible to get all unique array elements across all docs

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#112]
Each one of my docs has a ``tags`` attribute. I would like to get all unique tags.

Currently, what I do is I query to get all tags and then perform a map reduce to get unique ones.

```
        var mapped = results.map(function(o){
           return o.tags;
        }).reduce(function(prev,current){
          if (current && current.length > 0)
            return prev.concat(current);
          else
            return prev;
        },[]);

        return _.uniq(tags);
```

Is there a more efficient way of performing this?

**Comment by garrensmith** [comment]
This is a situation where it is better to use a view.
