### ISSUE TITLE
How to $elemMatch on multiple array elements?

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#113]
Hi,

Each doc in my DB has a key named ``tags`` which is of ``Array`` type. I'd like to select docs with matching list of tags. 

It is simple to do so for a single tag but I am unable to do so for multiple tags.

I tried doing the following to match ``tag1`` && ``tag2`` with no luck:

```
      var query = {
        selector: {
          $and: [
            {_id:  {$gt: '0'}},
            {tags: { $elemMatch: {$eq: 'tag1'} }},
            {tags: { $elemMatch: {$eq: 'tag2'} }}
          ]
        }
      };
```

What's the correct way of matching on multiple elements?

**Comment by garrensmith** [comment]
Try using `$in` instead of `$elemMatch`

**Comment by andyepx** [comment]
Hi @garrensmith,

What is the correct syntax for $elemMatch, if one wanted to use it? I tried multiple combos of operators but they all seem to result in the whole index instead of the subset I was expecting to retrieve...

Thanks!

**Comment by garrensmith** [comment]
@andyepx something like this:

```js
  selector: {
    {_id:  {$gt: null}},
    {tags: { $elemMatch: {$eq: 'tag1'}}},
    }
}
```

But these [docs](https://docs.cloudant.com/cloudant_query.html#combination-operators) give a nice explanation and here is our [elemMatch tests for more examples](https://github.com/nolanlawson/pouchdb-find/blob/master/test/test-suite-1/test.elem-match.js).

**Comment by yattias** [comment]
Thank you, will give it a shot!

**Comment by andyepx** [comment]
Thanks @garrensmith, :+1: awesome work!
