### ISSUE TITLE
ddoc for find-indexes must differ from design document for map/reduce views  

### ISSUE THREAD

**Issue by cornelisse** [nolanlawson/pouchdb-find#115]
I discover that find() returns {} when the index is stored in the same design document (e.g _design/my_indexes) for map/reduce views. When ddoc (e.g. indexes) refers to another _design document (like _design/indexes) than everything works well.

I am not sure if this is specified somewhere in the documentation. (If I missed this, than my apologises in advance.) Nor if this is known / designed behaviour.

Either this is known behaviour and should be documented explicitly, and/or an proper error should be provided. Or it is a bug to be solved, some day :-)

**Comment by cornelisse** [comment]
I just read your page about "secondary indexes" again and noticed the strong advise to create one view per ddoc. If I follow your advice, this issue (#115) will not occur :-)

**Comment by garrensmith** [comment]
Thanks @cornelisse I will look and see if we can at least add a warning about this.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6284
