### ISSUE TITLE
$elemMatch on Object Arrays

### ISSUE THREAD

**Issue by dharmeshds** [nolanlawson/pouchdb-find#118]
Guys, first of all, cheers to your awesome work on Couch/PouchDB.

I would like to know if there is a way to query object arrays using $elemMatch, in a doc that looks something like;

```js
{ "_id": 'some_id'
  "request": 'request1',
  "events": [ {
  "eventId": 1,
  "status": 'completed' 
  }, {
  "eventId": 2,
  "status": 'pending' 
  }, {
  "eventId": 3,
  "status": 'pending' 
  }
] }
```

when I tried $elemMatch with an index on request and events I am getting all documents... Appreciate your urgent help since this is critical for completion of my current project..

**Comment by dharmeshds** [comment]
Hi Garren, I have read your issue #117, but it still returns me all docs even if I used another selector with $elemMatch..

**Comment by garrensmith** [comment]
@dharmeshds could you show me what your selector currently looks like?
Just for future reference, we not all guys here. So `Hi All` or `Hi everyone` is better than guys.

**Comment by dharmeshds** [comment]
{
              "request": 'request1',
              "activity": 'contactConnection',
              "events": { $elemMatch: 'U000018877766665196206231445227014795' },
            }

**Comment by dharmeshds** [comment]
:) Sorry... Hi all.. 
I tried several ways to select without success.. 

{
  "request": 'request1',
  "events": { $elemMatch: { "status": 'pending' } },
}

my index is on request and events..
I thought this should work based on MongoDb examples..

**Comment by garrensmith** [comment]
Try creating an index just for `request`. Then do something like this:

```javascript
{
  "selector": {
    "request": "request1",
    "events":{
      "$elemMatch": {
        "eventId": 4
      }
    }
  }
}

```

If that doesn't work. Then it is a bug in PouchDB. But you can also test via the Cloudant Dashboard or CouchDB Fauxton (master branch) to see if your query works against them. If it doesn't work against them then the query is wrong.

**Comment by dharmeshds** [comment]
when I tried this selector I get,
Error: unknown operator "a" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod or $all

**Comment by garrensmith** [comment]
What does your selector statement look like?

**Comment by dharmeshds** [comment]
db.find({
              "selector": {
                "request": 'request1',
                "events": {
                   "$elemMatch": {
                      "status": 'completed'
                    }
                }
              }
            }).then(printConsole).catch(logError)

**Comment by dharmeshds** [comment]
it works without events elemMatch in the selector.. index is just on request

**Comment by garrensmith** [comment]
Seems like a bug. I'll take a look when I get a chance.

**Comment by dharmeshds** [comment]
sure, thanks a lot for quickly looking into the issue.. I will also try this on Cloudant or Fauxton and let you know if it works.. appreciate your help..

**Comment by dharmeshds** [comment]
I debugged pouchdb-find and it certainly seems to be a bug in line 1422,
            return createCriterion(matcher, userValue[matcher], 'a')({'a': value});

the matcher becomes 0 for arrays and it is being compared in the switch statement for userOperator in line 1355 which eventually throws the above error..

**Comment by ronyrun** [comment]
Hello, 
I encounter as well some issues with $elemMatch.


The Index : 

                    {
                        index: {
                            fields: ['data.color', 'data.forms'],
                                name: 'name',
                                ddoc: 'ddocname',
                                type: 'json'
                        }
                    }

In my docs : 
1) data.color is a string.
2) data.forms is an array like ["rect',"square","triangle"]


This is Working :

                    selector: {
                        'data.categories': {
                            '$eq': ["rect',"square","triangle"]
                        },
                        'data.geohash' :propQuery.geohash,
                    }


This is not working : 

                    selector: {
                        'data.categories':{$elemMatch: "triangle"},
                        'data.geohash' :propQuery.geohash,
                    }

I encounter this error : `TypeError: Cannot use 'in' operator to search for 'startkey' in undefined`

**Comment by garrensmith** [comment]
@ronyrun currently there is a bug with $elemMatch that is cannot do in object matches. I'm hoping to fix it soon as I get some free time. Sorry that I cannot help you further.

**Comment by ronyrun** [comment]
Hi @garrensmith no worries !
I used a view instead

Thank you very much for your work

**Comment by ronyrun** [comment]
thank you GarrenSmith I'm gonna test it now.
