### ISSUE TITLE
pouchdb collate with pouchdb find

### ISSUE THREAD

**Issue by kristdev** [nolanlawson/pouchdb-find#119]
Hey, i want to use pouchdb collate and pouchdb find. i've created documents with and _id field like 1447923264692-54utilisateur.

I want to find docs using only _id field. I want to show docs where _id field contains 'one thing there'.

Can you help me? i want to use db.find(), but i don't know which selector i must use.

**Comment by garrensmith** [comment]
@kristdev I'm would guess you could do something like this:

```js
db.find({
   selector: {
     _id: { $gt: null},
     _id: {$regex: /one thing there/}   
});
```

**Comment by kristdev** [comment]
ok, i will test it, thanks

**Comment by nolanlawson** [comment]
Please reopen if you're still having an issue.
