### ISSUE TITLE
$in selector always returns all docs

### ISSUE THREAD

**Issue by Sigmus** [nolanlawson/pouchdb-find#120]
Hello. I'm having trouble understanding the ```$in``` operator usage.
At http://nolanlawson.github.io/pouchdb-find/ I tried this code:
```javascript
db.find({
  selector: {_id: {$in: ['falcon', 'fox']}},
  sort: ['_id']
}); // all docs returned
```
It doesn't matter what goes into the ```$in``` value when you run the code **it always fetches all documents**. I'm probably missing something, can someone please help?

**Comment by garrensmith** [comment]
You need another selector. From the [Cloudant Docs](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

```
You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.
```

**Comment by Sigmus** [comment]
Thank you for your reply. So using ```$gte```as the basis of our query:
```javascript
db.createIndex({
  index: {fields: ['debut']}
}).then(function () {
  return db.find({
    selector: {debut: {$gte: 1994}, _id: {$in: ['pikachu', 'puff']}}
  });
}); // returns ness, pikachu and puff
```
ness shouldn't be in the results... I'm still confused.

**Comment by garrensmith** [comment]
Sorry the version of PouchDB-find running on the github.io page is slightly older and has a bug in the $in operator. 

All misspelling thanks to my iPhone

**Comment by Sigmus** [comment]
I was able to understand how it works using Cloudant directly. Thanks again.
