### ISSUE TITLE
$in not implemented in selector option?

### ISSUE THREAD

**Issue by ThinklabsGbR** [nolanlawson/pouchdb-find#124]
Hey,

is it possible that $in currently can't be used as selector option? The following example returns wrong results

```javascript
newsDB.find({selector: {id: {'$in':[798159]}}}).then(function (result) {console.log(result)});
```

Am i doing something wrong?

Cheers,
Antony

**Comment by garrensmith** [comment]
Hi @ThinklabsGbR this should help you https://github.com/nolanlawson/pouchdb-find/issues/120

**Comment by garrensmith** [comment]
Bascially you ned another selector combined with `$in` for that query to work.

**Comment by ThinklabsGbR** [comment]
Ah i see..thanks very much, now it is working as expected!

Cheers,
Antony

**Comment by garrensmith** [comment]
Excellent.
