### ISSUE TITLE
Error with find()

### ISSUE THREAD

**Issue by isaacanet** [nolanlawson/pouchdb-find#125]
Hi, I am trying to find elements with Find() but always It returned "Error: couldn't find a usable index. try creating...". 
My data array is similar to:
```
var data = {
     name: 'Peter',
     moreData: {
         phone: 002356666,
         email: 'aaaa@bbbb.com'
     }
}
```

How do I find elements with phone key?

**Comment by garrensmith** [comment]
@isaacanet you would need to create an index with the fields `moreData.phone` and then you would need to query with the `moreData.phone`. If you don't know how to do that I would recommend reading the readme as well as the [Cloudant docs](https://docs.cloudant.com/cloudant_query.html#combination-operators).

**Comment by isaacanet** [comment]
I do it, but when I want to find by phone returns error.
My code is: 

```
db.createIndex({
      index: {
        fields: ['actor.firstName']
      }
    }).then(function (result) {
      db.find({
        selector: {moreData: {phone: 002356666}}
      }).then(function (r) {

      }).catch(function (err) {
        console.log(err)
      })
    }).catch(function (err) {
      console.log(err)
    })
```

**Comment by garrensmith** [comment]
The issue here is  you are creating an index on `actor.firstName` but then querying on something different. You need to do this instead:

```js

db.createIndex({
      index: {
        fields: ['moreData.phone']
      }
    }).then(function (result) {
      db.find({
        selector: {'moreData.phone': 002356666}}
      }).then(function (r) {

      }).catch(function (err) {
        console.log(err)
      })
    }).catch(function (err) {
      console.log(err)
    })
```

**Comment by isaacanet** [comment]
Now It's working! Thanks! Technical failure...
