### ISSUE TITLE
Unable to make a simple find

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-find#128]
I don't think it's a bug, it's just that I don't know where to ask my question. I'm trying to make a simple request without success.

           tspPouch.createIndex({
                index: {
                    fields: ['type']
                }
            }).then(function (result) {
                console.log(result);
                tspPouch.find({
                    selector: {type: 'cover'}
                }).then(function (result) {
                    console.log(result);
                }).catch(function (err) {
                    console.log(err);
                });
            }).catch(function (err) {
                console.log(err);
            });

I get the error: "Error: couldn't find a usable index. try creating an index on: type"

So I think I didn't understand how the index works... Can anyone help me to understand what's wrong in my find function?

**Comment by garrensmith** [comment]
@natcohen that should work. I can only imagine their is a typo or something. Which version of CouchDB are you using and what version of pouchdb-find and pouchdb.

**Comment by natcohen** [comment]
@garrensmith I'm using v0.7.0 of find, 5.0.0 of pouchdb and 1.6.1 of couchdb!

It really drives me crazy...I don't see any typo and the index is successfully created.

**Comment by garrensmith** [comment]
You cannot use pouched-find with CouchDB 1.6.1. you need to use either Cloudant, PouchDB-server or CouchDB from the master branch.
That could be your issue.

**Comment by natcohen** [comment]
Oh...I see! I'm surprised that couchdb affects pouchdb-find behavior. I thought pouchdb was independent and could sync with couchdb but according to what you say, it seems that pouchdb shares more with couchdb than a sync...

**Comment by garrensmith** [comment]
It depends on what your connection string is. If you specify a url then it connects to that CouchDB instance. If you just specify a database name then it will use the browser’s database. Most likely indexDB.

**Comment by natcohen** [comment]
Well in my case I have a localDB that sync with a remote CouchDB...and getting this behavior.

BTW what do you mean by CouchDB master? Do you mean CouchDB 2 beta?

**Comment by garrensmith** [comment]
Ok if you remove the sync part do you still get the issue? If so I think I will need to see a larger gist of your code.
CouchDB master — CouchDB from git master branch.

**Comment by natcohen** [comment]
@garrensmith Hey Garren, I removed the replication and still get the error. Should I clean my cache and recreate my DB?

**Comment by nolanlawson** [comment]
Closing because this sounds more like tech support than an issue. FWIW, StackOverflow and the #pouchdb IRC are also good channels for this kind of discussion. :)
