### ISSUE TITLE
MutliSelector issues

### ISSUE THREAD

**Issue by kwstoikonomou** [nolanlawson/pouchdb-find#129]
Working on latest Chrome:

__$or not working__
I want to find all docs with firstName starting with "Venk", OR lastName starting with "Mario".
So i am doing the following:
```javascript
db.find({
  selector: {
               $or: [
                  {firstName: {$gte: "Venk", $lte: "Venk\uffff"}},
                  {lastName: {$gte: "Mario", $lte: "Mario\uffff"}},
               ]
  },
limit: 5
}).then(function (result) {
  console.log(result);
})
```
and i get the following error:
Uncaught (in promise) Error: couldn't find a usable index. try creating an index on: $nor. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields

It seems to not understand that "$or" is a reserved term. Replacing $or with $and does NOT produce the same error

__$and issues__
The following 3 expressions should have been translated all to: **(firstname > "Mario") AND (firstname <= "Mario\uffff")**. But that doesnt seem to happen

```javascript
db.find({                            //This works as supposed...
  selector: {
               $and: [
                  {firstName: {$gte: "Mario"}},
                  {firstName: {$lte: "Mario\uffff"}}
               ]
  },
limit: 5
})

db.find({                             //.....this does too
  selector: {
                  firstName: {$gte: "Mario", $lte: "Mario\uffff"},
  },
limit: 5
})

db.find({                              //.....this doesn't
  selector: {
                  firstName: {$gte: "Mario"},
                  firstName: {$lte: "Mario\uffff"}
  },
limit: 5
})
```

Similarly these 2 don't, both,  work correctly
```javascript
db.find({                          //wrong behavior. seems to only take 2nd $and into consideration
  selector: {
               $and: [
                  {firstName: {$gte: "Venkov"}},
                  {firstName: {$lte: "Venkov\uffff"}}
               ],
               $and: [
                  {lastName: {$gte: "Mario"}},
                  {lastName: {$lte: "Mario\uffff"}}
               ]
  },
limit: 5
})

db.find({                          //correct behavior
  selector: {
               $and: [
                  {firstName: {$gte: "Venkov"}},
                  {firstName: {$lte: "Venkov\uffff"}},
                  {lastName: {$gte: "Mario"}},
                  {lastName: {$lte: "Mario\uffff"}}
               ]
  },
limit: 5
})

**Comment by garrensmith** [comment]
@kwstoikonomou first off instead of doing `{$gte: "Venkov"}, {$lte: "Venkov\uffff"}` you can do 
`{$eq: "Venkov"}.

Then for `$or`, it needs to be combined with another selector because that part is done via in memory processing. I explain it a bit in this [blog post](http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find).

So something like this could work

```
db.find({
  selector: {
               _id: {$gte: null},
               $or: [
                  {firstName: {$eq: "Venk"}},
                  {lastName: {$eq: "Mario"},
               ]
  },

```

**Comment by kwstoikonomou** [comment]
> @kwstoikonomou first off instead of doing {$gte: "Venkov"}, {$lte: "Venkov\uffff"} you can do 
`{$eq: "Venkov"}.

I think that is wrong. Doesn't $eq mean "equal"?? I don't want the firstname to be equal to "Venkov". I want the firstname to start with "Venkov"... That is why i do the "\uffff" character trick. Am i wrong somewhere i don't understand?

**Comment by garrensmith** [comment]
Sorry I misunderstood you are correct. 

All misspelling thanks to my iPhone

**Comment by kwstoikonomou** [comment]
What about the $and behavior?
Shouldn't all the mentioned cases work the same? At least i think that is the intuitive way to do things.

**Comment by angelxmoreno** [comment]
@garrensmith  please reopen this issue until it is confirmed as a bug. I am getting the same error
@kwstoikonomou please show the code showing how you are defining your indexes

**Comment by kwstoikonomou** [comment]
Not sure what has to do with the $and problems but here it is how i create my indexes:

```javascript
con.createIndex({
                    index: {
                        fields: ['firstName', 'lastName']
                    }
                })

```

**Comment by angelxmoreno** [comment]
@kwstoikonomou I was having the same error message and was trying to debug while comparing your syntax. I came across #27 Order of index fields matter when using sort 
That seem to fix my issue. 

Also, the reason why the examples you mention do not all work the same is because they are not properly syntaxed objects. 
```js
var query = {
    name: 'Bob',
    name: 'Bobby'
};
console.log(query); // gives you {name: 'Bobby'}
```

Hope that answers your question.

**Comment by kwstoikonomou** [comment]
@angelxmoreno 
I don't have sort on my query so i don't encouter that problem. Altough i seem to remember stumbling upon such an "unexplained" issue when initially experimenting with PouchDB.

Your comment about incorectly syntaxed objects is dead-on! I should have spotted that.
So the "un-intuitive" behavior of $and is not a PouchDB error, is a Javacript problem.

All in all thanks for your comment. You have been a major help
