### ISSUE TITLE
db.createIndex return value

### ISSUE THREAD

**Issue by zeroware** [nolanlawson/pouchdb-find#13]
I'm calling createIndex like it's documented but the return value is just an empty object and not a promise.

```javascript
var indexResult = db.createIndex({
        index: {
            fields: ['date']
        }
    }).then(function (result) {
        console.log(result);
    }).catch(function (err) {
        console.log(err);
    });

console.log(indexResult); //returns {}
```

**Comment by nolanlawson** [comment]
Yep, the return value is a Promise. What you're looking for is the `result`, not the `indexResult`. Read this guide if you're not sure about promises: http://pouchdb.com/guides/async-code.html

**Comment by nolanlawson** [comment]
Also, depending on the browser, when you try to log a Promise, it may look like `{}` instead of a Promise object.
