### ISSUE TITLE
Unable to create an index

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-find#130]
I think this one is a bug...

I use angular 1.4, pouchdb-find 0.8.0, pouchdb 5.0.0 and Chrome 47.0.2526.73

I initialize my database:

        var db = new PouchDB('newdb', {auto_compaction:true, size: 50});

        db.replicate.to('https://login:pass@myDB.cloudant.com/newdb', {live:true})
        db.replicate.from('https://login:pass@myDB.cloudant.com/newdb', {live:true})

And have a service like this one

        find:function(){
            var deferred = $q.defer();
            pouchDB.createIndex({
                index: {
                    fields: ['type']
                },
                type : 'text'
            }).then(function() {
                return pouchDB.find({
                    selector: {type: 'cover'},
                    sort: ['type']
                })
            }).catch(function (err) {
                console.log(err);
                deferred.reject(err);
            });
            return deferred.promise;
        },

In my controller I call the service:

    myService.find().then(function(result){
        console.log(result);
    });

But get the following error: `Error: couldn't find a usable index. try creating an index on: type. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.(…)`

**Comment by garrensmith** [comment]
Could you try doing `db.createIndex and db.find` instead of `pouchDB.find`

**Comment by natcohen** [comment]
Well pouchDB is the name of my service that returns my DB (db) so it doesn't really matter, it's just for the structure of my app.

Anyway, I did what you asked (put the find right after initializing the db in the same service) and got the same problem...

**Comment by garrensmith** [comment]
Could try it without the replication setup. You can only query once the createIndex promise has resolved otherwise it will fail. 

All misspelling thanks to my iPhone

**Comment by natcohen** [comment]
@garrensmith I removed the replication and got the same result... In addition, as you can see from my code, the find is performed only when the createIndex has been resolved!

**Comment by Sigmus** [comment]
@natcohen What happens when you log createIndex's result?

**Comment by nolanlawson** [comment]
@natcohen Can you enable debug mode and try again? In debug mode, it will print out all the indexes it found and why it didn't choose one.

**Comment by natcohen** [comment]
@nolanlawson I enabled the debugger and I get that:

    pouchdb:find creating index +0ms _design/idx-1fb2ce0f95850b501398c4897433bec5
    pouchdb-find-0.8.0.min.js:1 pouchdb:find planning query +2s Object {selector: Object, sort: Array[1]} (the object being my request)

However when I try to display the indexes after creating it;
    
    find:function(){
        var deferred = $q.defer();
        pouchDB.createIndex({
            index: {
                fields: ['type']
            },
            type : 'text'
        }).then(function() {
            pouchDB.getIndexes().then(function (res) {console.log(res)})
            return pouchDB.find({
                selector: {type: 'cover'},
                sort: ['type']
            })
        }).catch(function (err) {
            console.log(err);
            deferred.reject(err);
        });
        return deferred.promise;
    },
I get the following:

`Object {indexes: Array[1], total_rows: 1}
indexes: Array[1]
0: Object
ddoc: null
def: Object
fields: Array[1]
0: Object
_id: "asc"
__proto__: Object
length: 1
__proto__: Array[0]
__proto__: Object
name: "_all_docs"
type: "special"
__proto__: Object
length: 1
__proto__: Array[0]
total_rows: 1`

**Comment by nolanlawson** [comment]
Yeah, somehow you don't have any indexes. You have a single array with the built-in `_all_docs` index and no others.

I don't know how it happened, but your `createIndex()` failed, or it's not ready by the time you query. I think the issue might be the `type: 'text'`.

**Comment by nolanlawson** [comment]
Or it could be the `type`. Not sure unless you can provide a live test to reproduce.

**Comment by ameernuri** [comment]
Got the same error. Here's the `createIndex()`
```
db.createIndex({
  index: {
    fields: ['kind', 'text']
  }
}).then(function (result) {
  console.log("index created")
}).catch(function (err) {
  console.log("there's an error")
});
```
When I run it, it logs `index created` but it comes after the error message. It used to say `...try creating an index on: type. Make sure...` but I changed the `type` field to `kind` and now it says `...try creating an index on: . Make sure...`

**Comment by vijender007** [comment]
I am also getting the same error on my local machine. So needs to have a solution for it.

**Comment by Sigmus** [comment]
I created a fiddle: https://jsfiddle.net/sigmus/t400cq0r/ – so we can try to pinpoint the problem.

![image](https://cloud.githubusercontent.com/assets/155508/12054008/eb844a86-af05-11e5-8275-02078fd77816.png)

The above image shows the console output.

**Comment by garrensmith** [comment]
If I use @Sigmus jsfiddle I cannot recreate this issue. Even if I add `type: text` when creating the index.

**Comment by natcohen** [comment]
If someone needs my db to debug this, I would be happy to share it.

Do you think it comes from the db or something else?

**Comment by natcohen** [comment]
BTW for me the new 0.9.0 solved my issue...

**Comment by garrensmith** [comment]
Brilliant. Thats good to hear.
