### ISSUE TITLE
How to filter subdocument fields

### ISSUE THREAD

**Issue by trungtin** [nolanlawson/pouchdb-find#132]
I have some thing like this:
```
{docs: [
"link": {
  "data": {
    "facebook": {
      "name": "Facebook",
      "url": "//facebook.com/"
    },
    "google": {
      "name": "Google",
      "url": "//google.com/"
    },
    "twitter": {
      "name": "Twitter",
      "url": "//twitter.com/"
    },
    "reddit": {
      "name": "Reddit",
      "url": "//reddit.com/"
    },
  }
}
]}
```
and I want to filter some object, e.g. `"facebook"` and `"google"`, I thought this should work:
`db.find({selector: {_id: {$eq: 'link'}}, fields: ['data.facebook', 'data.google']}).then(doc => console.log(doc))`
but it not, it return like this `{'data.facebook': undefined, 'data.google': undefined}`
Is there anyway to do this? Thanks very much.
Edit: Of course I can get the whole doc and filter in JS, but if there're 10000 of it, is there any performance hit, or it the same if filter by pouchDB ?

**Comment by garrensmith** [comment]
Could you show me what a document looks like. I don't understand the example above.

**Comment by nolanlawson** [comment]
You need `'link.data.facebook'`, not `data.facebook`.

**Comment by trungtin** [comment]
Thanks for your reply.
But actually, it doesn't work. I have solved it by filtering in JS, but if you want to take a look, I have a simple fiddle here: https://jsfiddle.net/wf4xu1xd/

**Comment by nolanlawson** [comment]
Thanks for your fiddle! And sorry, but I mistyped. You want `data.facebook.name`.
