### ISSUE TITLE
how to use with angular

### ISSUE THREAD

**Issue by dedoyle** [nolanlawson/pouchdb-find#134]
I don't know where to put this code
PouchDB.plugin(require('pouchdb-find'));

**Comment by garrensmith** [comment]
Straight after you have required PouchDB

**Comment by dedoyle** [comment]
thx. I know that, but I'm not using requirejs with angular. I use PouchDB without using require.

**Comment by nolanlawson** [comment]
If you are using Angular 1, then just include the script in your page:

```html
<script src="pouchdb.js"></script>
<script src="pouchdb.find.js"></script>
```

If you are using `angular-pouchdb`, then follow their instructions to make it work with pouchdb-find: https://github.com/angular-pouchdb/angular-pouchdb#does-this-work-with-pouchdb-plugins
