### ISSUE TITLE
Stuff I dislike about Mango

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-find#138]
I don't know where else to put this, but I want to create an issue to track all the stuff that I found I really really disliked about Mango as I was writing this plugin, but can only really be fixed by changing the Mango specification/implementation.
- [ ] `$exists` is in-memory - this is totally unnecessary. if you can do `$gt: null` on an indexed field, then you should be able to do `$exists: true` because it's exactly the same thing
- [ ] `$elemMatch` is in-memory - I think we should just auto-index arrays, because otherwise people have absolutely no way of doing a simple thing like categories/tags in `pouchdb-find` and are forced to use map/reduce instead
- [x] you can't search without a selector - this should just basically do an `allDocs`. there's no reason to throw an error
- [ ] `sort` needs to use exactly the same fields as the selector (see #137)

I'm going to hit up the Cloudant folks and see if we can't iterate to solve some of these things. One of the promises of pouchdb-find/Mango is that it makes querying P/CouchDB easier, but these four things really bug me because they will invariably trip up any new user who tries to use this plugin.

**Comment by nolanlawson** [comment]
So I guess the thing I'll do is create a JIRA for each issue and then link to it from here

**Comment by EuAndreh** [comment]
Check with @janl what's the most suited way to do this.

**Comment by janl** [comment]
+1 on filing a JIRA with CouchDB. These are good suggestions!

**Comment by garrensmith** [comment]
I've added the following JIRA tickets for this:

* https://issues.apache.org/jira/browse/COUCHDB-2926
* https://issues.apache.org/jira/browse/COUCHDB-2927
* https://issues.apache.org/jira/browse/COUCHDB-2928
* https://issues.apache.org/jira/browse/COUCHDB-2929

I'll reach out to @tonysun83 and the rest of the Cloudant team that could help on this.

**Comment by tonysun83** [comment]
@garrensmith @nolanlawson : Appreciate the suggestions and feedback! I'll address each JIRA ticket separately and tag you guys to open up discussion.

**Comment by nolanlawson** [comment]
Thanks a lot @garrensmith!

**Comment by millette** [comment]
Item 3 above ([jira-2928](https://issues.apache.org/jira/browse/COUCHDB-2928)) is fixed in [mango-27](https://github.com/apache/couchdb-mango/pull/27), hourray!

**Comment by natcohen** [comment]
Is it true that selectors have to match EXACTLY (no less no more) the index fields? If it is then it is clearly something I dislike... There is no reasons why we can't search for less fields than the index!

**Comment by garrensmith** [comment]
Hi @natcohen, that is not the case. PouchDB-find will try and match on less depending on which fields you use. Then with pouchdb-find 0.10 and above if it cannot find an index it will default to using `_all_docs` and do your query in memory. It will give you a warning if it does that because it can be slower. 

> There is no reasons why we can't search for less fields than the index!

This seems a bit harsh. I would recommend reading this [blog post](http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find) that explains how pouchdb-find works underneath so you can see why in most cases it will need all the fields. 

The other way to solve it is to create multiple indexes with reduced fields. That way pouchdb-find will always match.

**Comment by natcohen** [comment]
@garrensmith Sorry, I didn't mean to be harsh! Thanks for the link, it was really helpful to understand... 

Btw would it be possible to index all fields separately so queries with $or could be done by multiples queries and then be aggregated? And $and queries could be also done separately and results not in all queries might be removed?

It's hard to come from the SQL world and see such limitations...so I'm just wondering if there is any future solution in the no-SQL world to have more flexibilities with queries?

**Comment by nolanlawson** [comment]
closing because this was just mostly discussion
