### ISSUE TITLE
$text support

### ISSUE THREAD

**Issue by youknowriad** [nolanlawson/pouchdb-find#141]
Hello,

I would like to know if there's any chance to have support for the $text operator.

Thanks a lot

**Comment by nolanlawson** [comment]
It's not currently being developed, but it's a desirable feature, yes! :)

**Comment by mfilotto** [comment]
Could this feature fit in the actual code ? Or would it need a complete rewrite ?

**Comment by mfilotto** [comment]
@nolanlawson For you what would be the best way to implement that feature ? A merge with quick-search plugin maybe ?

**Comment by garrensmith** [comment]
@mfilotto for Cloudant/CouchDB $text uses a Lucene backend. We would have to find an equivalent for the frontend to build it on top of. Not the easiest task. I think we will first focus on getting standard pouchdb-find out of beta first.

**Comment by brandonaaron** [comment]
I'd actually like to see this at least as a pass-through option for those backends that support it and where pouchdb is just being used as a client.

**Comment by garrensmith** [comment]
It should in theory just pass those through to the backends already

**Comment by natcohen** [comment]
I've tried to use this plugin with a remote DB and it doesn't seem to work (I don't get any feedback - no result, no error). He is what I've tried:

    this.cloudant.find(
                {"selector": {"$text" : "some text"}}
            ).then((result)=> {
                console.log(result);
            }).catch((error)=> {
                console.log(error);
            }
    );

In Cloudant I have created the following index:
```
{
    "type": "text",
    "index": {}
}
```

@garrensmith Any suggestion?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6281
