### ISSUE TITLE
$exists not working

### ISSUE THREAD

**Issue by dflourusso** [nolanlawson/pouchdb-find#142]
Following [THIS](https://github.com/nolanlawson/pouchdb-find#dbfindrequest--callback) docs, i am trying to execute a find as [THIS](https://github.com/nolanlawson/pouchdb-find#sorting).

But i'm getting the error bellow:
> couldn't find a usable index. try creating an index on: myField. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.

It isn't supported more?

**Comment by garrensmith** [comment]
@dflourusso $exists is working. Can you show me your full query. You need to combine $exists with another query. See [this article](http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find) for more detail on this

**Comment by paliari** [comment]
I'm working in the same project of @dflourusso, and i'm getting this problem too.
See bellow two examples. The first one is about use *$in*, and the second is which @dflourusso had mentioned.

```
db.createIndex({index: {fields: ['name']}}).then(function () {
    db.find({selector: {name: {$in: [5, 6]}}}).then(function (r) {
        console.log(r);
    })
});

db.createIndex({index: {fields: ['name']}}).then(function () {
    db.find({selector: {name: {$exists: true}}}).then(function (r) {
        console.log(r);
    })
});

```
> Error: couldn't find a usable index. try creating an index on: id. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.

**Comment by garrensmith** [comment]
You need another selector. This blog post explains it in more detail http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find

All misspelling thanks to my iPhone

**Comment by paliari** [comment]
Tank you, it is working now.
