### ISSUE TITLE
pouchdb-find and ember

### ISSUE THREAD

**Issue by thedeadkoiclub** [nolanlawson/pouchdb-find#145]
Sorry, for this very basic question ... How do I make the pouchdb plugins work in ember? I'm currently trying this with pouchdb-find.
I have pouchdb working smoothly via ember-pouch.
Pouchdb-find is installed by `bower install pouchdb-find`.
I'm calling: `app.import("bower_components/pouchdb-find/dist/pouchdb.find.js");` in ember-cli-build.js
Now I'm lost on how to attach the plugin to the pouchdb. `Require('pouchdb-find')` in the application adapter gives me this:
Could not find module 'pouchdb-find' imported from '(require)' Error: Could not find module 'pouchdb-find' imported from '(require)'.

Help is very much appreciated.

**Comment by nolanlawson** [comment]
In case no one figured this, you need to `PouchDB.plugin(require('pouchdb-find'))`

**Comment by thedeadkoiclub** [comment]
Hey Nolan, thanks for answering. It turned out to be so trivial, that it seemed a dumb question after all. I just installed pouch-find via npm and used the app.import in the ember-cli-build.js Then all the methods of pouch-find (also true for other plugins) are already attached to the db. So no call of require or PouchDB.plugin necessary here. Thanks anyway.
