### ISSUE TITLE
Can't seem to be able to sort by ascending order?

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#147]
Hi Pouchdb-find team,

I have the following query: 

      var searchQuery = {
        selector: {
          $and: [
            {_id:  {$gt: null}}
          ],
          sort: [{_id: 'asc'}]
        }
      };

But my results are not sorted correctly.

"_id" is a string in my database. Each record has the following:

![screen shot 2016-01-21 at 9 42 55 am](https://cloud.githubusercontent.com/assets/802819/12483517/7ba0cd96-c023-11e5-9681-863e981cf0bd.png)

The function responsible for executing the query is:

```
Store.prototype.getDocsByQuery = function(query){
  var db = this.localDB;
  return new Promise(function(resolve, reject){
    db.find(query).then(function(result){
      resolve(result.docs);
    }).catch(function(err){
      console.log("Error", err);
    });
  });
};
```

Any insight into what is happening?

**Comment by garrensmith** [comment]
Could you supply some examples of what your ids look like. Along with how they should be ordered

All misspelling thanks to my iPhone

**Comment by yattias** [comment]
Hey @garrensmith The IDs are numeric strings. They are created by javascript's ``Date.now()``

Here is an example:

![screen shot 2016-01-21 at 1 40 00 pm](https://cloud.githubusercontent.com/assets/802819/12490661/ad17d8c6-c044-11e5-905e-f2b8e0f242a5.png)

I'd like for them to be order either by ascending or descending order.

**Comment by cemarta7** [comment]
Im having the same problem when trying to sort.

db.createIndex({
      index: {
        fields: ['name','type'],
        name:"contacts"
      }
    })

db.find({
        selector: {
          name: { $gt: null },
          type: { $eq: 'contact' }
        },
        fields: ['_id', 'name'],
        sort:[{'name':'asc'}]
      })

sorting is happening by _id not by name

**Comment by garrensmith** [comment]
Thanks for reporting, I'll take a look soon as I can.  If either of you could write a failing test then I can take a look and see how to fix it. Or help you fix it you want. 

All misspelling thanks to my iPhone

**Comment by cemarta7** [comment]
Actually its working. It just being case insensitive. how can I apply a function to make them lower case before sorting?

**Comment by yattias** [comment]
Ah, never mind. I had my ``sort`` in my selector. Closing...
