### ISSUE TITLE
Error: couldn't find a usable index. 

### ISSUE THREAD

**Issue by he-yang** [nolanlawson/pouchdb-find#151]
Hi,

I am using pouchdb-find to do "tag" search locally on my pc with indexedDB.
All docs include a 'tags' field which is an array filled with tags, e.g. ['tagA','tagB','tagC']

1st, createindex like this.
db.createIndex({
	  index: {
		fields: ['tags']
	  }
	}).then( //do my db.find here)

2nd, I am trying to search for docs with a certain tag :

db.find({
		  "selector": {
			"tags": {
			  "$elemMatch": 'tagB' // I also tried "$elemMatch":{"$eq":"tagB"}
			}
		  }
		})

but I got the following error.
Error: couldn't find a usable index. try creating an index on: tags. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.

later I modified the tags field from an array into a string like this      tags: "tagA tagB tagC" and I thought $regex might work on this.

db.find({
		  "selector": {
			"tags": {
			  "$regex": 'tagB' 
			}
		  }
		})
but, I got the same error above.

Something wrong with my code?  $regex, $elemMatch not working on indexed fields?

**Comment by garrensmith** [comment]
hi @he-yang you need another selector this [blog post]([http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find) will explain it in a bit more details.

**Comment by he-yang** [comment]
thank you for your reply. problem solved, and $regex and $elemMatch can only work "in-memory".
anyone else encounter the same issue can add {_id:{$gt:null} to your selector object and try again.

**Comment by garrensmith** [comment]
Great to hear.
