### ISSUE TITLE
How can I query for unique array elements across DB?

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#152]
Hi,

Every doc in my database has a ``tags`` property which consists of an array of strings. Different docs can contain the same tags.

For example:

```
    docA: {
      _id: "1234567",
      tags: ["foo", "bar"]
    },
    var docB: {
      _id: "9876543",
      tags: ["bar", "baz"]
    }
```

What I need to do is to collect all unique tags across all docs.

Should I be using ``$elemMatch`` for this instead of a design doc? If so could you please provide an example? @nolanlawson mentioned a while back ``$elemMatch`` in #46 so I wanted to check first before I go and create a design doc for this.

Thanks for your help!

**Comment by garrensmith** [comment]
$elemMatch is working now and should help you here.

**Comment by yattias** [comment]
Hey @garrensmith I forgot to post my question in the issue. I just updated it.

What I need to do is to collect all unique tags across all docs. Is $elemMatch the operation of choice in such a case? How would I go about using it to query for unique tags across user docs? Thank you.

**Comment by garrensmith** [comment]
You cannot do that via pouchdb-find. Best to use a map-reduce view for that.

**Comment by yattias** [comment]
Okay that's what I suspected. Thank you.
