### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'startkey' in undefined(…)

### ISSUE THREAD

**Issue by agozie** [nolanlawson/pouchdb-find#153]
I upgraded to 0.9.0 from 0.7.0. I started getting this: `TypeError: Cannot use 'in' operator to search for 'startkey' in undefined(…)` for this query :
 `db.find({
        selector: {
          tID: this.test.tID,
          due: {
            $exists: true
          },
          terms: {
            $exists: true
          }
        }
      })`
What am I doing wrong please?

**Comment by garrensmith** [comment]
I'm not sure. If you could add a failing test in a PR I can then take a look. 

All misspelling thanks to my iPhone

**Comment by andrewdep** [comment]
I'm seeing this too... Did you figure out what was going wrong, @agozie?

**Comment by natcohen** [comment]
Have the same problem here...

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6277

**Comment by botverse** [comment]
You can reproduce it like this:

```javascript
db.createIndex({
  index: {
    fields: ['field1', 'field2'],
  },
})
  .then(() => {
    console.log('this will work');
    return db.find({
      selector: { field1: 'xxx' },
      sort: [ { field1: 'asc' }, { field2: 'desc' }],
    });
  })
  .then(() => {
    console.log('this won\'t');
    return db.find({
      selector: { field1: 'xxx', field2: {} },
      sort: [ { field1: 'asc' }, { field2: 'desc' }],
    });
  });
```

**Comment by nolanlawson** [comment]
@botverse can you please move discussion to http://github.com/pouchdb/pouchdb/ ? the `pouchdb-find` repo is in the process of being moved into the pouchdb monorepo, sorry for the confusion!
