### ISSUE TITLE
0.9.0 $exists no longer working

### ISSUE THREAD

**Issue by martinwoitzik** [nolanlawson/pouchdb-find#156]
Hi there,

I made an update to v0.8.0 and also to 0.9.0 and after updating the module I can no longer query my database with '$exists: true' queries. It always shows the following error message: "Error: couldn't find a usable index. try creating an index on: title. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.(…)"
That's weird because checking for the appropriate index on 'title' tells me that it already exists. I also removed the whole database and reindexed all fields, but the same error still occurs. All other queries, e.g. $eq or $gt seem to work fine.

To reproduce the issue try to query a database with the following find-object:
```javascript
db.find({
  selector: {
     'title': { $exists: true }
  },
  limit: 10,
  sort: [{'title': 'asc'}]
});
```

**Comment by martinwoitzik** [comment]
Until 0.7.0 the queries worked fine!

**Comment by garrensmith** [comment]
You need another selector. See this blog post for more details
http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find

**Comment by martinwoitzik** [comment]
Which one do I have to take? I read the article but it doesn't cover anything on '$exists' ?!
I don't want to look for a specific title, just all articles sorted by title / ascending or descending.

**Comment by martinwoitzik** [comment]
Ok, now I seem to have found it:
```javascript
selector: {
   'title': {
      $gt: null
   }
}
```
It looks really weird to me but it works.
