### ISSUE TITLE
Modifier for $regex

### ISSUE THREAD

**Issue by mfilotto** [nolanlawson/pouchdb-find#158]
Would be nice to have a way to set case insensitive modifier with $regex
A mango DSL limitation I guess ?

**Comment by garrensmith** [comment]
It should be standard regex. So pouchdb-find is JavaScript regex and mango is erlang regex. So that should work. If it doesn't a failing test would really help us fix it. 

All misspelling thanks to my iPhone

**Comment by mfilotto** [comment]
Here is the code to do the exact test they have in Mango
````
    it('should do a regex search with case sensitive modifier ', function () {
      var db = context.db;
      var index = {
        "index": {
          "fields": ["name"]
        }
      };
      return db.createIndex(index).then(function () {
        return db.find({
          selector: {
            name: {$gte: null},
            series: {$regex: "(?i)Mario.*"}
          },
          sort: ['name']
        }).then(function (resp) {
          var docs = resp.docs.map(function (doc) {
            delete doc._rev;
            return doc;
          });

          docs.should.deep.equal([
            { name: 'Donkey Kong', rank: 7, _id: 'dk', series: 'Mario',
              debut: 1981, awesome: false },
            { name: 'Luigi', rank: 11, _id: 'luigi', series: 'Mario', debut: 1983, awesome: false },
            { name: 'Mario', _id: 'mario', rank: 5, series: 'Mario', debut: 1981, awesome: true },
            { name: 'Yoshi', _id: 'yoshi', rank: 6, series: 'Mario', debut: 1990, awesome: true },
          ]);
        });
      });
    });
````

**Comment by garrensmith** [comment]
That regex is how erlang does it. For that to work in pouchdb you need to follow these rules

https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags

**Comment by mfilotto** [comment]
You're right the right pattern would be more like `/mario.*/i`
The problem is that RegExp constructor splits modifiers/flags from the rest of the pattern :
`new RegExp(pattern[, flags])` 

So maybe pouchdb-find could extract that part from `userValue` and call the constructor with modifiers here : 
https://github.com/nolanlawson/pouchdb-find/blob/0458b74d445457c55bc01096a19c3e35e6115045/lib/adapters/local/find/in-memory-filter.js#L188

**Comment by garrensmith** [comment]
Nice catch. This is a nice first fix if you want to do the work? I'm happy to help you where you need.

**Comment by mfilotto** [comment]
@garrensmith OK I'm on it

**Comment by mfilotto** [comment]
@garrensmith need help, I have a bad time running tests.
They reach my couchdb but fail with error 'Something wrong with the request'
Any idea ?

**Comment by garrensmith** [comment]
You need to use CouchDB 2.0 or if you using docker from `klaemo/couchdb:2.0-dev`. You most have only 1 node running ideally on port `15984` You also need to enable cors by running this https://github.com/nolanlawson/pouchdb-find/blob/master/bin/enable-couchdb-cors.sh

**Comment by mfilotto** [comment]
@garrensmith ok I'll try this config

**Comment by natcohen** [comment]
@mfilotto any news about this?

**Comment by mfilotto** [comment]
@natcohen I'm stuck with the docker env.
I can't have `klaemo/couchdb:2.0-dev`working to replay all the tests

**Comment by natcohen** [comment]
@mfilotto unfortunately not into docker stuff...can't you install the normal version? Or even test it on cloudant? Maybe @garrensmith can help with docker

**Comment by mfilotto** [comment]
Here is my reflexion for that feature.
It would be nice to add modifiers but I face several interrogations.

My first approach is to parse the given string and extract the modifier if the pattern of the string is something like `'/pattern/modifier'`

This could be easilly done. But it is semanctically wrong in regard to the [RegExp Javascript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) that can be created eather through a `constructor('pattern', 'modifier')` or with a litteral notation` /pattern/modifier`

But if we accept litteral notation how the users will dynamically create that notation ?

Do you think that we can accept the notation `'/pattern/modifier'` anyway ?

**Comment by natcohen** [comment]
I think that it would be a good start to accept the literal notation

**Comment by colinskow** [comment]
For a local PouchDB query you can simply pass in a Javascript object `/mario/i`. I'll ask Cloudant support how they handle flags since it isn't in the documentation.

**Comment by garrensmith** [comment]
I don't think we can. Underneath Regex for Cloudant Query/CouchDB mango is
just erlang regex. So it will always be a little different compared to
javascript regex.
https://github.com/apache/couchdb-mango/blob/master/src/mango_selector.erl#L496

**Comment by colinskow** [comment]
I verified that I can pass in a literal Javascript regex object to a local `pouchdb-find`, but of course that won't work with Cloudant or CouchDB.

**Comment by nolanlawson** [comment]
@colinskow That sounds like a reasonable workaround; you can just use regular regexes for local and string regexes for remote. Closing unless someone thinks there's a fix we can reasonably do for this.

**Comment by colinskow** [comment]
There are two REGEX flags that Erlang and Javascript have in common, `i` for case insensitive and `m` for multiline.

In Erlang this is accomplished by prefixing the regex string with `(?im)`. This is invalid in Javascript and will throw an error. In Javascript there is no way to set flags directly from the regex string.

What I want to do for local is search for `(?[flags])` at the beginning of the string, and convert to Javascript regex.

For remote search, if the user passes in a Javascript regex object with flags `i` or `m` set, it will convert this to an Erlang string.

How does that sound @nolanlawson ?

**Comment by colinskow** [comment]
See: http://stackoverflow.com/questions/37157723/cloudant-query-couchdb-mango-how-to-set-regex-flags

**Comment by nolanlawson** [comment]
> What I want to do for local is search for (?[flags]) at the beginning of the string, and convert to Javascript regex.

Hmmm, I'd kinda prefer to have a more foolproof method. Can we accept a JavaScript regex and then convert it to a string and possible an Erlang regex string as necessary? When you call `.toString()` on a JavaScript regex, it seems we can determine whether it's case-insensitive or not:

```
> /foo/i.toString()
'/foo/i'
```

**Comment by colinskow** [comment]
I think the goal is to have the behavior as similar as possible across both Cloudant/CouchDB 2.0 and local PouchDB.

In Cloudant:

```json
"series": {
      "$regex": "(?i)mario"
    }
```

will do a case insensitive search for "mario". We should translate this to Javascript so it will work on a local `pouchdb-find`. And if the user passes a Javascript RegEx object to a remote `find`, we can check for the `i` and `m` flags and convert it to an Erlang expression.

We'll never be able to guarantee that Erlang and Javascript regexes will perform exactly the same, but we can support major use cases where the API is equivalent.

**Comment by llin96** [comment]
I test this and it works

```javascript
var regexp = new RegExp(keyword, 'i');
{name: {'$regex': regexp}};
```

**Comment by rhysdavies1994** [comment]
thank you @llin96! this may be handy on the readme until a proper solution is implemented?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6274

**Comment by samdutton** [comment]
Belated thanks for this!

FWIW plain old literals work as well: 

```
localDB.find({
    selector: {name: {$regex: /.*Mario.*/i}}
});
```
