### ISSUE TITLE
Find relational object

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-find#160]
I was wondering if it's possible to find a relational object? Let's say I have the following objects:

{name:'Joe',
type:'Person',
age:32,
job:'PL'}

{type:'Jobs',
language:'English',
PL:'plumber',
EL:'electrician',
...}

Is it possible to find Joe with the attribute job:'plumber'?

**Comment by EuAndreh** [comment]
Well, as far as I know, that is not possible in the way you are seeking (making some sort of SQL-like JOIN).

I see 2 solutions to your problem:
1. Make two queries
2. Put 'plumber' in the 'Joe' document, instead of 'PL'

**Comment by natcohen** [comment]
@EuAndreh thanks...that's what I feared! Your first solution makes it very difficult to manage a clean query and your second solution wouldn't allow me to use different languages.

Is there any plan with couchdb 2 to implement a sort of join?

**Comment by garrensmith** [comment]
The best way to do a join is via a Map/reduce view
http://www.cmlenz.net/archives/2007/10/couchdb-joins

**Comment by nolanlawson** [comment]
You may also want to look into relational-pouch: https://github.com/nolanlawson/relational-pouch

Closing because I think this is out of the scope for `pouchb-find`.
