### ISSUE TITLE
createIndex() does change even the design document already existed.

### ISSUE THREAD

**Issue by 5amfung** [nolanlawson/pouchdb-find#161]
It seems like when `createIndex()` is called, even though the design document already exists, I would still get a change notification from `changes()`.  According to the explanation in README.md, I thought `createIndex()` doesn't do anything if the design doc already exists.  I also notice that more rows are created in my indexeddb and the `seq` is also increased.

```
db.createIndex({ index: { ddoc: 'by_name', name: 'by_name', fields: ['name'] }})
```

**Comment by ramonsan** [comment]
The same happens to me, result returned is "exists" but it stills incrementing _rev_ of _design doc.

**Comment by mfilotto** [comment]
Same here rev is incremented each time.
As I sync with a remote db, I also have many push and pull because of that issue.

For now I filter the push this way (not sure it's the better way)

```
        this.db.sync(remoteDB, {
            live: true,
            retry: true,
            push: {filter: function (doc) { return !doc._id.startsWith('_design/idx-'); }}
        })
```

**Comment by numerized** [comment]
Same here, rev is incremented and has been responsible of a huge drop in performance over time as a query _bulk_docs?revs=true appeared out of nowhere, deleting all the revisions from the created indexes solved my problem

**Comment by chadfawcett** [comment]
I have tested this with connecting to a remote CouchDB and the function is working as expected (not incrementing the revision). So this may only be an issue when creating an index on a local database.

**Comment by numerized** [comment]
Thanks for the info @chadfawcett for now I'm using @mfilotto push filter and it's perfect.

**Comment by chadfawcett** [comment]
@numerized I've already been filtering my push, but find it kind of annoying to have so many revisions. 

I'm working on a potential fix now.

**Comment by garrensmith** [comment]
Thanks @chadfawcett for fixing this. I've pushed a new npm version with this fix in.

**Comment by numerized** [comment]
Cool I'll try it now then
