### ISSUE TITLE
pouchdb-find not available on bower.io

### ISSUE THREAD

**Issue by ashleybrener** [nolanlawson/pouchdb-find#162]
Please can you publish on bower.io for package manager installation.

when searching `pouchdb-find` the response is:

```
You search didn't return any results. Please try a different keyword.
```

Thank you.

**Comment by nolanlawson** [comment]
`bower install pouchdb-find` works fine for me. I'm using bower v1.7.7. Try updating Bower or maybe `bower cache clean`?

Also just FYI, most JavaScript library authors are starting to move away from Bower and toward npm. `pouchdb-find` is also available via npm.

Closing, please reopen if still an issue.
