### ISSUE TITLE
No view error the first time, but works fine afterward.

### ISSUE THREAD

**Issue by 5amfung** [nolanlawson/pouchdb-find#163]
I'm trying to following the suggestion in http://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html to start building the index as soon as the index is created.  However, I always get the following error first time when indexeddb is empty.  It's always the first time with an empty indexeddb.  It works afterward.

```
not_found: ddoc folders_view has no view named folders_view
```

Code

```
    let viewName = 'folders_view';
    this.db.createIndex({
        index: {
            ddoc: viewName,
            name: viewName,
            fields: ['name']
        }
    }).then(result => {
        if (result.result === 'created') {
            this.db.query(viewName, { stale: 'update_after' });
        }
    }).catch(console.error.bind(console));
```

**Comment by nolanlawson** [comment]
Yeah, seems like a bug. Thanks for reporting!

**Comment by malfusion** [comment]
Is this bug fixed? I keep running into the same issue once in a while. Is there any way we can be notified when the index views are ready to be used? A hook maybe?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6272
