### ISSUE TITLE
Field dot notation does not seem to work.

### ISSUE THREAD

**Issue by dsmeltz** [nolanlawson/pouchdb-find#164]
I have the following fields specified:

`"fields": ["_id", "info"]`

and receive the following as a result against a local PouchDB:

```
{
   "_id":"85-somedude-1456174210512",
   "info":{
      "zeeId":"85",
      "lastUser":"somedude",
      "lastSaved":"2016-02-23T18:12:06.389Z",
      "version":"0.1.0",
      "id":0
   }
}

```
"info" is an object with multiple properties on it and the entire object is returned. That's what I would expect.

When I try to do this, against the same PouchDB:

`"fields": ["_id", "info.lastSaved"]`

I don't get anything except "_id":

```
{
    "_id":"85-somedude-1456174210512"
}
```

**Comment by castrinho8** [comment]
Yes, it doesn't work, eventually you can query only by "_id" and then use javascript [filter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) to select "info.id"

**Comment by colinskow** [comment]
Is there a test for this in the test suite?

**Comment by colinskow** [comment]
This is the offending function: https://github.com/nolanlawson/pouchdb-find/blob/master/lib/utils.js#L142

It has no support for dot notation. I'll take care of it over the next few days and do a PR with test added.

**Comment by colinskow** [comment]
OK, I've got this fixed. But the tests from master are a mess and are failing all over the place. We need to get these working so I can verify that my PR doesn't break anything.

**Comment by garrensmith** [comment]
I have a branch and PR for the test fixes. But I'm waiting for some bug fixes in mango first. 

All misspelling thanks to my iPhone

**Comment by colinskow** [comment]
Shall I submit the PR anyway? I've unit tested it manually and it seems to work fine.

**Comment by garrensmith** [comment]
Yes please that would be awesome. But we will probably only be able to merge once we fixed master. 

All misspelling thanks to my iPhone.




On Fri, May 20, 2016 at 3:57 AM -0700, "Colin Skow" <notifications@github.com> wrote:












Shall I submit the PR anyway? I've unit tested it manually and it seems to work fine.

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pouchdb-find/pull/189
