### ISSUE TITLE
Can't find usable index (even with indexes created)

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-find#168]
I've created index but pouchdb-find doesn't find it (Error: couldn't find a usable index.)...when I put getIndexes() I get all my indexes.

My index has 5 fields and my search uses only two of them.

Another strange behavior is that when I go on my couchDB instance on the index, it doesn't display anything and the "progress circular" continues to move indefinitely.

It used to work but I had to clear the cache and since then, nothing!

Here is the debug log:

pouchdb:find planning query +18s 
Object {selector: Object}
selector: Object
nickname: Object
$regex: "^.*Albert.*$"
__proto__: Object
type: Object
$eq: "entity"
__proto__: Object__proto__: Object__proto__: Object
tsp-services.js:655 Error: couldn't find a usable index. try creating an index on: type, nickname. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.

**Comment by colinskow** [comment]
I ran into this problem too. Your index has to have the exact same fields as your query. This makes it run most efficiently.

Another option (what has worked for me) is one field for index:

```js
    var indexFields = ['type', 'date', 'description', 'details', 'amount'];
    var setup = [];
    indexFields.forEach(function(field) {
      setup.push( db.createIndex({ index: { fields: [field] } }));
    });
    var ready = Promise.all(setup);
```

**Comment by nolanlawson** [comment]
Yep, I think we can safely close this. It's a confusing aspect of Mango, but this is just how it's designed unfortunately. 😕

**Comment by colinskow** [comment]
@nolanlawson what you need to do is make the README documentation clear about what is valid and what is not. Write an index trouble-shooting guide. Cloudant's docs are quite confusing.

I've spent hours pulling my hair out and I am still not personally clear on how it works.

**Comment by natcohen** [comment]
@colinskow thanks for the tip... I've tried your technic of indexing each field but I still ran into troubles. For example:
`selector: {
      $or: [
        {type: 'animal'},
        {type: 'human'}}
      ],
      name:'John'
    }` 
does't work. 
@nolanlawson The problem here is that I have 20 fields and it would be impossible to make indexes for all the possible combinations. Do you have any solution for that?

**Comment by colinskow** [comment]
@natcohen try creating a free Cloudant account and run your queries there. Cloudant is the reference implementation so if it works there but not with a local `pouchdb-find` then file a bug.

**Comment by natcohen** [comment]
@colinskow Thanks, that's a good idea but it would be better to understand what pouchdb-find is capable of...

**Comment by nolanlawson** [comment]
@colinskow Yes, I hope that at some point we can modify the PouchDB docs/guides themselves to include pouchdb-find docs. That can happen after pouchdb-find gets pulled in to core.

Cloudant query also keeps changing, and so it'll be good to keep the docs up to date. Honestly I mostly learned Cloudant query by writing this thing. :/

**Comment by natcohen** [comment]
@nolanlawson by specifying in the doc what can be done with the current version you would avoid a lot of filed issues. It will also make it more accessible to people... I guess. I'm still not clear with what can or can't be done.

**Comment by garrensmith** [comment]
@natcohen and @colinskow you have good points. It would be great if you could help with the documentation. We using CouchDB master branch as reference as it has a few more fixes than Cloudant. Cloudant will roll all those fixes into prod soon.

**Comment by colinskow** [comment]
Mango doesn't have very good documentation and it takes some trial and error to figure out. Basically the search indexes spit out map reduce keys which are arrays. Your query must be translatable into a `start_key` and `end_key` based on that index or it will either fail, or fall back to an inefficient memory query of the entire db.

This article sheds a little bit of light on the underlying system:
https://cloudant.com/blog/mango-json-vs-text-indexes/#.V0Qrd1e4FSU

**Comment by garrensmith** [comment]
I tried to explain it a bit more here
http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find

**Comment by nolanlawson** [comment]
BTW the next version of pouchdb-find will provide warnings rather than errors when there's no usable index.
