### ISSUE TITLE
Searching for null

### ISSUE THREAD

**Issue by froatsnook** [nolanlawson/pouchdb-find#169]
A query like `db.find({ selector: { day: null } })` doesn't work: (TypeError: Cannot use 'in' operator to search for '$ne' in null(…)), whereas a query like `db.find({ selector: { day: { $eq: null } } })` does!

Is this because of the Cloudant query API?  I quickly glanced at the docs and see anything.

Thanks for the library!  I started trying to do it myself (coming from Meteor), and was relieved to find this.

**Comment by froatsnook** [comment]
It seems there are other problems with null.

```javascript
var db = new PouchDB("test");
db.createIndex({ index: { fields: ["field1"] } });
db.createIndex({ index: { field: ["field2"] } });
db.post({ field1: null, field2: null });
db.find({ selector: { field1: null } }); // fails as described in previous post
db.find({ selector: { field1: { $eq: null } } }).then((res) => console.log(res)); // OK, returns 1 doc
db.find({ selector: { field2: { $eq: null } } }).then((res) => console.log(res)); // OK, returns 1 doc
db.find({ selector: { field1: { $eq: null }, field2: { $eq: null } } }).then((res) => console.log(res)); // WRONG, returns empty array
```

**Comment by garrensmith** [comment]
Those look like bugs. Thanks for reporting. If you could create some
failing tests in the test suite that would be really helpful.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6270
