### ISSUE TITLE
http://nolanlawson.github.io/pouchdb-find/ issue

### ISSUE THREAD

**Issue by telekosmos** [nolanlawson/pouchdb-find#171]
Hi
Dunno whether or not this is the right place to file this issue (sorry if not) but trying a simple `$regex` example on the playground website I am getting:
```
createNoIndexFoundError@http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2145:19
planQuery@http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2166:34
http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:1663:30
promiseReactionJob@[native code]
```

using the query
```js
db.createIndex({
  index: {fields: ['series', 'debut']}
}).then(function () {
  return db.find({
    selector: {series: {$regex: '^Mario'}},
    sort: [{series: 'desc'}, {debut: 'desc'}]
  });
});
```

Cheers!!

**Comment by garrensmith** [comment]
Hi @telekosmos 

you need another selector this [blog post](http://www.redcometlabs.com/blog/2015/12/1/a-look-under-the-covers-of-pouchdb-find) will explain it in a bit more details.
