### ISSUE TITLE
Indexes replication issue

### ISSUE THREAD

**Issue by andreujuanc** [nolanlawson/pouchdb-find#172]
Hello,
I created an index, use it and works perfectly. But then when I tried to sync it gave me an error that i dont have access for that.

Im using pouchdb-authentication and for now all users have all permissions.  

What is the correct way to fix this? 

- Delete the index after usage so hopefully it doesnt get synced?
- Use Query instead of find?
- Maybe there is a way to use find with preexisting indexes created in the remote db?
- Filter the replication so it doesnt sync design documents

Thanks!!

**Comment by nolanlawson** [comment]
It depends on which kind of backend you're trying to sync with. Keep in mind that Mango queries are only supported in Cloudant, Couch 1.7, and Couch 2.0.

In general, though, it sounds like your particular issue is a 403 related to not having permissions to create _design documents. In those cases the simplest solution is to use filtered replication to avoid syncing _design documents. Hope that helps!
