### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by froatsnook** [nolanlawson/pouchdb-find#174]
Hi,

I got react-native-pouchdb working (i.e. react-native-sqlite-storage as a websql adapter), and now I'm trying to get pouchdb-find working.  The system is quite unstable -- sometimes I can get insert and then a find to work, but other times the database gets locked up somehow.  The only clue I have before just giving up is the following:

```
error in _pouch_Tasks
sqlite.core.js:562 Object {code: 6, message: "UNIQUE constraint failed: local-store.id"}
```

I logged all the transactions and found two suspicious looking transactions:

```
BEGIN
INSERT INTO 'local-store' (id, rev, json) VALUES (?,?,?)
p1: "_local/indexes"
p2: "0-1"
p3: "{"views":{"idx-Tasks_day/idx-Tasks_day":{"Tasks-mrview-23295376d72329945b5bc85d197260a7":true}}}"
```

and:

```
BEGIN
INSERT INTO 'local-store' (id, rev, json) VALUES (?,?,?)
p1: "_local/indexes"
p2: "0-1"
p3: 
"{"views":{"idx-Tasks_dueDate/idx-Tasks_dueDate":{"Tasks-mrview-a7a172c943daf3a928b3fa7fb9fbba74":true}}}"
```

These are two indexes I'm creating like this:

```javascript
    const fields = ["dueDate"];
    db.createIndex({
      index: {
        fields,
        name: `idx-${dbName}_${fields.join("-")}`,
        ddoc: `idx-${dbName}_${fields.join("-")}`,
      },
    });
```

(I had the same problem when I let the index and ddoc name be chosen automatically)

I did some grepping and realized that this might be a pouchdb issue and not a pouchdb-find issue.  But I'm hoping you can at least point me in the right direction!

1. Have you used pouchdb-find with react-native?
2. Do any of the above transactions look familiar?

Thank you!  I'm a bit sad now because pouchdb and pouchdb-find have been working so great for me in the web version of my product, and I'm really hoping to not have to switch databases!!!

**Comment by garrensmith** [comment]
I think @nolanlawson has some experience with all of this.

**Comment by froatsnook** [comment]
OK with further testing I am still getting this error, but it doesn't seem to affect the stability.  Rather it seems like having more than one database is causing the issue (even with pouchdb-find disabled)!

**Comment by nolanlawson** [comment]
Sounds like you have uncovered a bug in the SQLite engine for React Native (whatever is under the hood in react-native-sqlite-storage). This is a pretty common occurrence we're run into with SQLite adapters; they're usually very buggy and it isn't until you have a big heavy database like PouchDB that people uncover this stuff.

I'm working on porting [node-websql](https://github.com/nolanlawson/node-websql) to React Native. When that's ready, please switch over. Until then, consider React Native support very, very experimental. 😅

**Comment by nolanlawson** [comment]
BTW the reason that I can confidently say it's not our bug is because PouchDB's WebSQL engine has been confirmed working on an enormous test suite on multiple browsers (PhantomJS, Chrome, Safari) as well as node-websql and [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2). So if another WebSQL engine fails it's almost undoubtedly a bug in that engine.

**Comment by froatsnook** [comment]
@nolanlawson Thanks for the insight!  I am excited for node-websql in React Native :).

**Comment by andpor** [comment]
what is the version of sqlite-storage you are using? Can you send more information or file a bug with cordova-sqlite-storage which is the baseline for the react-native impl? Will try to fix it...
