### ISSUE TITLE
correct way to find _id = uuid Or excluding _design\ 

### ISSUE THREAD

**Issue by gustavomick** [nolanlawson/pouchdb-find#178]
i need to use uuid as id, and as far as could understand i cant use selector._id = {$regex: '^[0-9a-f]'} or something simliar. 

which is the right way to get only docs (not design etc)? or this a bug / future feature and till now i have to use query().

i guess i missing something from wiki/documentation so any help regarding this will be great. 
thank you

**Comment by gustavomick** [comment]
well.. now im using uuid.v4().toUpperCase(), so then i can use selector._id = {  $lt: '_' } .. anyway i dont know if there is a better way. thanks.

**Comment by nolanlawson** [comment]
Yeah, unfortunately the only way is to do `{$gt: '_design/\uffff'}` etc. Sorry about that.

**Comment by gustavomick** [comment]
np. nice work thanks.

**Comment by garrensmith** [comment]
The latest version of CouchDB mango supports doing a query with just `$regex`. I'm working on a patch to add that support to PouchDB-find. Will hopefully have it done soon.
