### ISSUE TITLE
FIELD WOOO! is output on console

### ISSUE THREAD

**Issue by jonotron** [nolanlawson/pouchdb-find#180]
This little beauty logs to console when my `$elemMatch` query runs :)

https://github.com/nolanlawson/pouchdb-find/blob/64f5c7b7fb2552405a426e4664cbbb6157e1f23f/lib/adapters/local/find/in-memory-filter.js#L223

I assume this is non intended.

**Comment by garrensmith** [comment]
Yes I left that in by mistake. A celebration of getting elemMatch working. You welcome to submit a patch to remove it. 

All misspelling thanks to my iPhone
