### ISSUE TITLE
Can't get $regex to work at all...

### ISSUE THREAD

**Issue by colinskow** [nolanlawson/pouchdb-find#183]
From Nolan's demo. I am following Cloudant's example of using `{_id: {$gt: null}}`. What am I doing wrong?

```js
db.createIndex({
  index: {fields: ['series']}
}).then(function () {
  return db.find({
    selector: {
      _id: {$gt: null},
      series: {$regex: 'Mario'}
    },
    sort: [{series: 'desc'}]
  });
});
```

returns...

```
createNoIndexFoundError@https://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2145:19
planQuery@https://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2166:34
https://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:1663:30
promiseReactionJob@[native code]
```

**Comment by garrensmith** [comment]
Can you try again without the sort part.

**Comment by colinskow** [comment]
Same problem :-(

**Comment by garrensmith** [comment]
These might help you
https://github.com/nolanlawson/pouchdb-find/blob/master/test/test-suite-1/test.regex.js

**Comment by colinskow** [comment]
OK, got it working. But I think it is a bug that `_id: {$gt: null}` is throwing a no index error. `_id` shouldn't need an index since it is default.

```js
db.createIndex({
  index: {fields: ['name']}
}).then(function () {
  return db.find({
    selector: {
      name: {$gt: null},
      series: {$regex: '^M'}
    }
  });
});
```

**Comment by colinskow** [comment]
Thanks @garrensmith !

**Comment by garrensmith** [comment]
No problem, I'll keep this open and take a look when I can.

**Comment by colinskow** [comment]
I tested this on Cloudant and the behavior is exactly the same. It is not a PouchDB Find issue. The problem was sorting on a non-primary index. I removed the sort and it works fine.
