### ISSUE TITLE
add total_rows to response of find API

### ISSUE THREAD

**Issue by chandu0101** [nolanlawson/pouchdb-find#19]
haha sorry mate , i need this one again in find :) , could you please throw some pointers ..

**Comment by nolanlawson** [comment]
I don't believe that find() implements it. The goal is to reproduce the Cloudant query language exactly, so if they don't support it, it's a no-go for pouchdb-find..  They might have something similar though.

**Comment by chandu0101** [comment]
oh no! , what about pagination :s

**Comment by nolanlawson** [comment]
Weird, I don't see anything in their API to support anything even remotely similar (e.g. `$count`). Maybe we should open up an issue on the CouchDB JIRA to start discussing this.

**Comment by chandu0101** [comment]
created an issue https://issues.apache.org/jira/browse/COUCHDB-2644

**Comment by francescoagati** [comment]
Hi,
i think that the time for processing the issue is very slow. Isn't possible expose this fields only for the local's query?

**Comment by standup75** [comment]
+1

**Comment by moQuez** [comment]
Apparently there is a fix already: https://github.com/apache/couchdb-mango/pull/6

**Comment by nolanlawson** [comment]
Oh sweet. Looks like I can implement it now. :)

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/pouchdb-find/commit/967e98114426bee524e0e1dfa321d73e218ba3b0
