### ISSUE TITLE
Cannot sort when find a document

### ISSUE THREAD

**Issue by opaulet92** [nolanlawson/pouchdb-find#204]
Hello,

I tryed a lot of things but I have the save problem. When I execute this next code, I have this problem : 
Error: Cannot sort on field(s) "reportId" when using the default index

```js
dbPouchDB.createIndex({
          index: {
            fields: ['reportId']
          }
        }).then(function(result) {
          dbPouchDB.find({
            selector: {reportId: 10},
            fields: ['reportId'],
            sort: [{reportId: 'desc'}],
            limit: 1
          });
        }).then(function(result) {
        }).catch(function(err) {
        });
```

I look at indexes and I have two. First one is the created index for reportId, and second one is the _all_docs.

When I look at the code from pouchdb-find, I see when the _all_docs index is defined, I cannot sort any field from "find" method.

Any ideas ? 

Best regards.

**Comment by nolanlawson** [comment]
This looks like a bug. Can you write a test case to reproduce (e.g. a live HTML file)? Glancing at your code I feel like we already have a number of tests that cover this case, so I'm not sure why it's failing.

**Comment by opaulet92** [comment]
I cannot get you a live HTML file because I use angularJs and a lot of modules I will show you.

I'm using these dependencies : 
- "angular-pouchdb": "^4.3.0",
- "pouchdb-find": "0.10.3"

In my app.js, I wrote : 
`
var app = angular.module('moduletest.app', [
  ...
  'pouchdb',
  ...
`

In my file that I use pouchDB object : 
`
angular.module('test.reports').service('TestReports', TestReports);
TestReports.$inject = ['$q', '$log', 'Database', 'Constants', 'pouchDB'];

function TestReports($q, $log, Database, Constants, pouchDB) {
   function getMaxReportId() {

      var deferred = $q.defer();

      // Storage PouchDB
      var dbPouchDB = pouchDB('my_database');
      if (!dbPouchDB) {
        console.log('Error pouchDB');
      } else {
        dbPouchDB.createIndex({
          index: {
            fields: ['reportId', 'type']
          }
        }).then(function(result) {
          return dbPouchDB.find({
            selector: {
              type: 'report',
              reportId: {$type: 'number'}
            },
            fields: ['reportId'],
            sort: [{reportId: 'desc'}],
            limit: 1
          });
        }).then(function(result) {
          if (result.docs.length === 0) {
            logger.trace('Max reportId not found!');
            deferred.resolve(parseInt(10));
          } else {
            deferred.resolve(parseInt(result.docs[0].reportId));
          }
        }).catch(function(err) {
          logger.trace('Error : ', err.message);
          deferred.reject(err.message);
        });
      }
      return deferred.promise;
    }
}
`

With this code, I have the problem I told you in the last post.
When I execute the next code to see indexes, I see two indexes. 
Here is the code : 

`
dbPouchDB.getIndexes().then(function(result) {
	console.log(result);
});
`

And the result is (here is the png): 

"_all_docs"
"_design/idx-1307a71464d6d5b4f4460b6b9f983c38"

Sorry for the late response, but I hope you can help me about this problem for me.
Best regards.

**Comment by nolanlawson** [comment]
I'm sorry, without a live test case it's really hard to deduce the error. I'll try to reproduce your error when I get a chance but I can't promise I'll be successful.

BTW I notice that you are using deferreds and that in your first code sample you forgot a `return` inside the promise chain. You may benefit from this article on promises which points out some common promise mistakes and how to fix them: https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

**Comment by opaulet92** [comment]
Yes, I know. You'll try to reproduce and we'll see.
Just to understand with promises. You told me I forgot a return inside the promise chain, but I don't understand even if your post "we-have-a-problem-with-promises" is very good. I have this code : 
`
dbPouchDB.createIndex(...).then(function(result) {
   return dbPouchDB.find(...);
}).then(function(result) {
   ...
}).catch(function(err)) {
});
`
Where is the problem ? Maybe, if I arrive to fix the return problem, maybe I will resove my problem on document sort.

Thanks a lot for this problem.

**Comment by nolanlawson** [comment]
@opaulet92 

```js
dbPouchDB.createIndex({
          index: {
            fields: ['reportId']
          }
        }).then(function(result) {
          // ----------> MISSING RETURN HERE <-------------
          dbPouchDB.find({
            selector: {reportId: 10},
            fields: ['reportId'],
            sort: [{reportId: 'desc'}],
            limit: 1
          });
        }).then(function(result) {
        }).catch(function(err) {
        });
```

I'll try to reproduce but it's much easier when you provide a live test case, e.g. a JSBin.

**Comment by opaulet92** [comment]
Hello,

I found the problem. It was not because I forgot a return (just I forgot it when I wrote this test case). 

In fact, It is a problem from 'sort' parameter on find method. For example, here is an example that It's works : 
`dbPouchDB.find({
            selector: {
              updateDate: {$gt: ''},
              type: 'report',
              customerId: String(customerId),
              deleteDate: {$type: 'null'}
            },
            sort: [{updateDate: 'desc'}],
            limit: limit
          });`

In fact, when I was debug the source code, I found there is 3 rules : 
- the sort and index parameters must be same and sort.length must be <= index.length
- the index and selector parameters must be same
- match field "selector[1st index]" must be [eq, gt, gte, lt, lte].

It is really weird thoses rules. In fact, in my example, I must write in selector "updateDate: {$gt:''}".

So, this is in fact this issue : https://github.com/nolanlawson/pouchdb-find/issues/137

**Comment by hdoedens** [comment]
Hi, I am having the same issue. My code:
```
dbFactory.createIndex({
    index: {
        fields: ['chapter']
    }
}).then(function(result) {
    return dbFactory.find({
        selector: { book: 'levenslied', chapter: {'$exists': true}},
        sort: [{ chapter: 'asc' }]
    })
}).then(function (res) {
    log.info('great!')
}).catch(function (err) {
    log.error(err)
});
```
I have read your blog about promises and returns and I think the code above should work. I also incorporated @opaulet92 suggestion by adding `chapter: {'$exists': true}}` to the selector.

@nolanlawson could you point me in the direction of the right solution to this? Manually sorting afterwards is really not an option.

**Comment by garrensmith** [comment]
You need to add book to your index and then sort on both

All misspelling thanks to my iPhone.




On Tue, Sep 6, 2016 at 1:28 PM +0200, "Harm Doedens" <notifications@github.com> wrote:












Hi, I am having the same issue. My code:

dbFactory.createIndex({
    index: {
        fields: ['chapter']
    }
}).then(function(result) {
    return dbFactory.find({
        selector: { book: 'levenslied', chapter: {'$exists': true}},
        sort: [{ chapter: 'asc' }]
    })
}).then(function (res) {
    log.info('great!')
}).catch(function (err) {
    log.error(err)
});




I have read your blog about promises and returns and I think the code above should work. I also incorporated @opaulet92 suggestion by adding chapter: {'$exists': true}} to the selector.



@nolanlawson could you point me in the direction of the right solution to this? Manually sorting afterwards is really not an option.

**Comment by hdoedens** [comment]
thanks @garrensmith for your suggestion. I have added `book` to my index and I am sorting on both now:
```
dbFactory.createIndex({
    index: {
        fields: ['book', 'chapter']
    }
}).then(function(result) {
    return dbFactory.find({
        selector: { 'book': 'levenslied', 'chapter': {'$exists': true}},
        sort: [{'book': 'desc'},{ 'chapter': 'asc' }]
    })
}).then(function (res) {
    log.info('great!')
}).catch(function (err) {
});
```
But now I am getting the same error as in #153 
Any Ideas?

**Comment by hdoedens** [comment]
@garrensmith adding book to the index and sort, was not the solution. I found #140 to state that `'$exists': true` != `'$gt': null`. So I replaced the former with the latter and now it works!
Thanks anyway for your suggestion!

**Comment by garrensmith** [comment]
Great. Can you close the issue

**Comment by hdoedens** [comment]
Sorry I can't close it, I don't see a close button, maybe the OP can.

Also I think the workaround is quite awkward and may be a bug?

**Comment by opaulet92** [comment]
Hello,
I'll come back in fiew weeks. I'll try to find out my problem with the other answers.

**Comment by opaulet92** [comment]
All is fine.

Thanks.
