### ISSUE TITLE
How to create views with pouchdb-find?

### ISSUE THREAD

**Issue by FlamesoFF** [nolanlawson/pouchdb-find#205]
For example:
I have DB with 1000 documents. 500 of them with "class": "person" and other 500 with "class": "company". How to create view in PouchDB to list companies or persons? Not an query, but a cached view.

Or can someone provide any link to a manual how to do this? Googled it  - no results.

**Comment by nolanlawson** [comment]
Just create an index on `class` and then query `{"class": {$eq: "person"}}`. This is the fastest way to do it in pouchdb-find currently; there is no faster way other than separating your typed documents into multiple PouchDBs, which is actually a smart choice given how IndexedDB works under the hood.
