### ISSUE TITLE
Multi-selectors

### ISSUE THREAD

**Issue by jtlindsey** [nolanlawson/pouchdb-find#209]
Hello, how do i use multi-selectors? When i have a db with 3 records type=post and 4 records type=comment and try something like this:

```
db.find({
  selector: {
    type: 'comment', 
    type: 'post'
  }
});
// returns 3 records
```
or

```
db.find({
  selector: {
    type: 'post', 
    type: 'comment'
  }
});
// returns 4 records
```
or
```
db.find({
  selector: {
    type: {$eq: "comment"},
    type: {$eq: "post"},
  }
});
// returns 3 records
```
I always get the last selector and not both. Using the current pouch core query, the following produces what I'm looking for:
```
db.query(function(doc) {
  if((doc.type == 'post') || (doc.type == 'comment')) {
    console.log(doc.type)
  }
});
// returns 7 records
```
So I also tried this with the plugin, but it throws an error because "$or" isn't allowed operator:
```
db.find({
  selector: {
    $or: [
      {type: "post"},
      {type: "comment" }
    ]
  }
});
```
So how do I query all records where type == "comment" || type == "post"?

**Comment by nolanlawson** [comment]
This is not a valid JS object:

```js
{
    type: {$eq: "comment"},
    type: {$eq: "post"},
  }
```

Most JS engines will just ignore the first `type` definition and use the second one.

As for your question, yes, the real fix here is to support `$or`, which is not currently supported. You can also fire off two simultaneous queries and then use `Promise.all()` to combine them.
