### ISSUE TITLE
Is there an equivalent of multiple emits?

### ISSUE THREAD

**Issue by tmld** [nolanlawson/pouchdb-find#21]
Hi there,

I had a play around and couldn't figure out how to achieve the equivalent of multiple emits using this plugin. Is there:
    a) A way to emit multiple values per document when creating an index, or
    b) A way to utilise existing PouchDB views when searching?

I'd like to be able to filter based on array values within the documents. For example, below (using the PouchDB query api) I can emit values for each actor in a movie and use this to find movies staring a particular actor.

Is there a way to achieve this using the pouchdb-find plugin?

<pre><code>// Source Data
var movies = [
  {
    "name": "The Godfather",
    "stars": [
      "Marlon Brando",
      "Al Pacino",
      "James Caan"
    ]
  }, ...
]

// Design document with multiple emits
{
	_id: '_design/stars',
	views: {
		'stars': {
			map: function (doc) {
				for(var i = 0; i &lt; doc.stars.length; i++) {
					emit(doc.stars[i]); 
				}
			}.toString()
		}
	}
}

// Query for stars (returns a result for "The Godfather")
db.query('stars', {key: 'Al Pacino', include_docs: true});
</code></pre>

**Comment by akircher** [comment]
I am glad you asked that @tmld, I am wondering the same thing. The only thing I could do currently was search one at a time e.g., `db.find({selector:'movies.stars.0'})`

Is this functionality in the cloudant spec?  I sure hope so!!!

**Comment by nolanlawson** [comment]
Yes, it's the `$in` operator, which is not implemented yet

**Comment by akircher** [comment]
Ok so in the example above you could search for Al Pacino with db.find({selector: {'movies':{$in:'stars'}}})?  How would you search for `Al` if the data was ```stars = [{first:'Al', last:'Pacino'}, {first:'Marlon', last:'Brando'}]```?

**Comment by nolanlawson** [comment]
Don't think you can, in that case.

**Comment by tmld** [comment]
Great, thanks @nolanlawson.

**Comment by akircher** [comment]
Wait I think it might be premature to close.  If this new API will eventually wholly replace Map/Reduce doesn't there have to be a way to search an array the objects such as [{first:'Al', last:'Pacino'}, {first:'Marlon', last:'Brando'}].  This data structure is very common.

Maybe the dot notations can solve this problem?  Not sure if the spec allows it, but can it be made to implicitly search arrays?  For example `db.find('movies.stars.first', 'Al')` would work for both `var movies = { stars:{first:'Al', last:'Pacino'}}` and `var movies = { stars:[{first:'Al', last:'Pacino'}]}`

**Comment by tmld** [comment]
Ok I've re-opened it.

I think what you are looking for will be covered by $elemMatch  when it is implemented, but we can leave this issue open until it's agreed if your use case will be met.

If I understand correctly, you should be able to do the following:
<pre><code>db.find({
	selector: {
		stars: {
			$elemMatch: {
				first: 'Al',
				last:'Pacino'
			}
		}
	}
});
</code></pre>

**Comment by akircher** [comment]
That's what I was looking for.  Thanks @tmld

**Comment by nolanlawson** [comment]
Also FWIW there will still be some things you can do with map/reduce that you cannot do with pouchdb-find. Map/reduce is super flexible in that you can basically run whatever JavaScript you want, so there will definitely be cases where pouchdb-find won't have an equivalent.

**Comment by garrensmith** [comment]
v0.7.0 now has `$elemMatch` support. So I'm now closing this.
