### ISSUE TITLE
Add total_rows for pagination purposes

### ISSUE THREAD

**Issue by keyiis** [nolanlawson/pouchdb-find#210]
I can't fint 'total' in find result,only 'docs' returned.i hope:
1、add 'total_rows','offset' to find result.
2、use same result format like pouchdb.query.

```
{
  "offset" : 0,
  "rows": [...{...}],
  "total_rows" : 4
}
```

**Comment by nolanlawson** [comment]
I could have sworn we supported `total_rows`, but checking the latest version of the code, I don't see it in there. Yeah, we should support `total_rows`.

**Comment by klanjabrik** [comment]
A workaround for this issue:

https://github.com/nolanlawson/pouchdb-find/blob/master/dist/pouchdb.find.js#L1669

```
    }),
    total_rows: res.total_rows,
    offset: res.offset
};
```

**Comment by Wvhf** [comment]
Hello nolan,

Any idea when you might be able to fix this issue ?

Kind regards

**Comment by garrensmith** [comment]
Unfortunately CouchDB Mango doesn't support `total_rows` or `offset`. Ideally with pouchdb-find we aim to copy CouchDB Mango functionality. So we won't support it until its in CouchDB Mango. You are welcome to send a mail to the dev mailing list on CouchDB to discuss it.

**Comment by SukantGujar** [comment]
@garrensmith, @nolanlawson : I am trying to find the relevant issue in CouchDB issue tracker, but haven't found anything so far. `find` solves so many querying scenarios (yay!) which really makes one miss the total rows count. Sadly, this limitation is going to keep us from chucking out our map-reduce views in favor of find :(. As this one's been there for some time now, I take that it may have fallen in favor of a different approach. Is there an alternative pagination experience which alleviates the need of total rows?
Thanks in advance!

**Comment by garrensmith** [comment]
@SukantGujar total_rows is never going to be accurate. It isn't even accurate in map/reduce. Total rows tells you how many total rows you have in an index. So in a map reduce instance, it will tell you how many rows were emitted. If you then query the index with `start_key` and `end_key` total rows will still only return the number of docs in the whole index not the number of rows for your query.

In pouchdb-find, underneath its using map/reduce, so it cannot return any useful total rows value. A quick and dirty way of doing pagination is to use skip. Depending on the size of your index this would work perfectly. So for a selector page 1:

```
{
   selector: {
    "name": "smith",
   },
   skip: 0,
   limit: 25
}
```

page 2 if you want 25 results per page:

```
{
   selector: {
    "name": "smith",
   },
   skip: 25,
   limit: 25
}
```

Performance will start getting affected if you going over 100000 or so rows ie:

```
{
   selector: {
    "name": "smith",
   },
   skip: 100000,
   limit: 25
}
```

But its best to test your use case.

**Comment by SukantGujar** [comment]
Thanks @garrensmith. For our usecase, it's important to provide the total count of matching records, irrespective of pagination. The data volume is not huge, but could get high enough to impact rendering when fetching all records in a single query. Is there an undocumented way of doing this?

**Comment by garrensmith** [comment]
I think the best you can do is Array.length once you have fetched the
results. I can't think of another way of doing that. We had this issue
while building pagination into Fauxton and had to come up with another
approach.

**Comment by Rolence** [comment]
Hello nolanlawson i have a problem retrieving documents using pouchdb-find plugin after performing document update on the document which changes the rev from 1 to 2.
