### ISSUE TITLE
db.find not throwing error when no index 

### ISSUE THREAD

**Issue by drschwabe** [nolanlawson/pouchdb-find#211]
According to the README if db.find is not able to find an index, it will throw an error.  However, on my setup with a fresh database that has no indexes, this basic find example does not throw an error: 

```javascript
//Try to do the find...
db.find({
  selector: { color: 'green' }, 
}, function(err, res) {
  if(err) console.log(err) 
  //Expecting an error if no index exists!
  return res.docs
})    
```
Instead, it returns the requested docs.

**Comment by garrensmith** [comment]
That behavior is correct and was a new change. I must have forgotten to update the readme. 
All misspelling thanks to my iPhone

**Comment by drschwabe** [comment]
Ok, then how would you recommend creating indexes 'on demand' ?   Originally I was planning to use this now defunct error handler to accommodate that.  Ex: 

```javascript
db.find({
  selector: { color: 'green' }, 
}, function(err, res) {
  if(err) {
     if(err.reason === 'no index exists') {
         //here is a nice spot to create an index if not already existing
     }
  return res.docs
})   
```

**Comment by garrensmith** [comment]
I wouldn't create indexes on demand. Rather define the indexes you need up front. That is a much better way of working. 

All misspelling thanks to my iPhone

**Comment by drschwabe** [comment]
Good tip but for my particular use case I do need them on demand since the selectors are dynamic; unknown in advance. 

So then if db.find does not throw an error, then to achieve the goal of an on demand index it seems db.createIndex would need to be called in advance of every db.find. 

```
 //Attempt to create an index: 
  db.createIndex({
    index: {
      fields: ['color']
    }
  }, function (err, res) {
    if(err) return console.log(err)
    //no error is thrown if index already exits, 
    //so now perform the lookup: 
    db.find({
      selector: { color: 'green' } 
    }, function(err2, res2) {
      if(err2) return console.log(err2)
      //and return just the matching doc: 
      return res2.docs
    })
  })    
```

Just seems messy though cause; say you suddenly have 100 async requests now instead of performing a one time db.createIndex based on a single error, (and then 100 db.finds) now we calling db.createIndex 100 times and db.find 100 times.    

That said, if db.createIndex overhead is negligible then I suppose the above code is fine in this case.

**Comment by nolanlawson** [comment]
If you have lots of indexes and they are dynamic, then you may want to look into Dexie.js or YDN-DB instead of Pouch. Pouch is not really optimized for the case where you have lots and lots of secondary indexes.

**Comment by drschwabe** [comment]
Ok, thanks for the recommendations.   Not necessarily a lot of indexes though - in the above example, the assumption is all 100 async requests have the same selector ie: { color: 'green' }.  My app just needs to create a handful of dynamic selectors; and want to ensure all subsequent db.finds perform fast. 

But I'll close this until/unless I find the above workaround is not performant; I haven't done a benchmark to compare the above workaround (using current pouchdb-find) vs the old version that offered an error handler when no index was found.  Ie: 100 async requests to db.createIndex + 100 db.finds vs 1 request to db.createIndex + 100 db.finds
