### ISSUE TITLE
Sorting with selector $exists uses the wrong index

### ISSUE THREAD

**Issue by dolfje** [nolanlawson/pouchdb-find#212]
When trying to sort on a field that is only selected by the $exists selector, gives an error.

> testDB = new PouchDB('test');
> testDB.createIndex({index: {fields: ["test"]}}).then(function() {
>  return testDB.put({_id: ""+Math.random(), "test": 5});
> }).then(function() {
>   return testDB.find({selector:{"test": {$exists: true}}, sort: ["test"]});
> }).then(function(ret) {
>   // Expect result, only get 
>   //Error: Cannot sort on field(s) "test" when using the default index
> });`

**Comment by dolfje** [comment]
I think the checkFieldsLogicallySound is wrong. There is checking if the index can be used. But that only works when the indexes are one of '$eq', '$gt', '$gte', '$lt', '$lte'. So $exists isn't added there. I've added $exists temporarely to logicalMatchers and my function works. Although I have to be honest, I don't have enough knowledge about the code base, to know the implications.

Also the code for isInvalidNe in that function does nothing. Because the hasLogicalOperator is false when $ne is used. So that part of the code cannot be triggered with $ne.

**Comment by dolfje** [comment]
And also $regex should be added to the logicalMatchers variable

**Comment by yoonwaiyan** [comment]
Any update on this issue? I'm having the same problem here, trying to sort based on a "date" field but getting the same error even after using indexes:

```
    expenses.createIndex({
      index: {fields: ['date']}
    }).then(function (result) {
      console.log("created index", result);
      return expenses.find({
        selector: {
          date: {'$exists': true}
        },
        sort: ['date']
      }).then(function (result) {
        console.log("result", result);
        dispatch({
          type: GET_ALL_EXPENSES,
          payload: result.rows
        });
      }).catch(function (err) {
        console.log("err", err);
        dispatch({
          type: GET_ALL_EXPENSES,
          payload: []
        });
      });
    }).catch(function (err) {
      console.log("index error", err);
    });
```

**Comment by htrampe** [comment]
Same problem here - any ideas?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6266
