### ISSUE TITLE
[Node.js] $lt with limit not working

### ISSUE THREAD

**Issue by txchen** [nolanlawson/pouchdb-find#215]
``` js
db.find({
    selector: { ts: { $lt: endts } },
    limit: 5,
    sort: [{ ts: 'desc' }]
  })
```

Code is like this. I have a collection indexed by ts. Every time I fetch more, it gives me 4 records instead 5. 

Versions:
"pouchdb": "^6.0.6",
"pouchdb-find": "^0.10.3",

Server:
pouchdb-server@1.2.0

**Comment by jkndrkn** [comment]
I am experiencing a perhaps related issue.

Here is my selector:

```
{
    "selector": {
        "_id": {
            "$gt": "surgery_case.",
            "$lt": "surgery_case.￿"
        }
    }
}
```

I have a database with hundreds of records. 32 of these have an _id that starts with the "surgery_case." prefix. If I do *not* set a limit, the above query only returns 25 of these records.

If I *do* set a limit of, say, 35 the above query will return all 32 records.

NOTE: The special character at the end of the `$lt` clause is the character with code `0xffff`.

**Comment by garrensmith** [comment]
CouchDB Mango defaults to only returning 25 docs. This is a configuration
option. I think in future releases you can configure it in the config.ini.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6263
