### ISSUE TITLE
Ionic Typescript Issue

### ISSUE THREAD

**Issue by saniyusuf** [nolanlawson/pouchdb-find#217]
Hi,
I am trying to use this plugin with Ionic via a typescript based project, I keep getting the following error  **Error TS2307: Cannot find module 'pouchdb-find'** from the typescript compiler. 

Any ideas?

**Comment by hadrien-toma** [comment]
Hi @saniyusuf !

Do you have seen this issue #201 ? It helped me to configure an Ionic 2 RC0 based project but maybe some manipulations could be useful in an other TypeScript based project.

**Comment by hichMEN** [comment]
after installing npm package `npm install pouchdb-find --save`
import it with : `import * as PouchFind from "pouchdb-find ";`
and add it to plugin: `PouchDB.plugin(PouchDBAuthentication);`
