### ISSUE TITLE
and/or with regex on same field

### ISSUE THREAD

**Issue by valepu** [nolanlawson/pouchdb-find#219]
Hello,
I have tried to use both an $and and an $or including a set of conditions ($regex) all on the same field, but it appears that only the last regex gets used (both using $and and $or)

Here's a plunker showing the issue: http://plnkr.co/edit/9N0xuC6k5iwPrY8QMca2?p=preview
This should show no results but it shows all of them instead, if you move the 2nd regex at the end it'll show only 1 result (the one starting with a b)

Checking a regex on different fields will work, but if the same field is checked multiple times then only the last regex will work

I'm not sure it's intended or not, i haven't found anything on the Cloudant API documentation but i admit i haven't read it thoroughly (although i've seen an example of an $or checking the same field multiple times, even though it was not a regex)

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6260
