### ISSUE TITLE
fulltext search?

### ISSUE THREAD

**Issue by ronag** [nolanlawson/pouchdb-find#222]
https://cloudant.com/blog/enable-full-text-search-in-apache-couchdb/#.WBZIu6OZNE4

Could we get support for the `_search` endpoint? and `indexes` in design documents.

**Comment by nolanlawson** [comment]
This could be done with Lunr.js ala pouchdb-quick-search but would be a lot of work and potentially a lot of code to bundle on the client side.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6259
