### ISSUE TITLE
Is Couchdb 2.0 currently supported??

### ISSUE THREAD

**Issue by jofomah** [nolanlawson/pouchdb-find#224]
Hi,

I have the following questions, because i am considering using Pouch-Find with CouchDB 2.0.

- Is CouchDB 2.0 currently supported??
- Does PouchDB allow one to query for a document and linked documents like MapReduce?

I.e if i have a Car document that is linked to CarType document via `car.type == carTypeID` can i return both documents in one query using PouchDB find???

**Comment by EuAndreh** [comment]
Hi @jofomah 

1. See #221 
2. As far as I understand, you can use the `$or` operator like:
```javascript
db.find({
  selector: {
    $or: [
      { _id: carTypeID },
      { type: carTypeID }
    ]
  }
});
```

**Comment by nolanlawson** [comment]
There is no `include_docs`, no, sorry. You can manually link _ids back to documents though.

**Comment by jofomah** [comment]
@nolanlawson @EuAndreh thanks
