### ISSUE TITLE
$nin doesn't work with _id

### ISSUE THREAD

**Issue by Chozzle** [nolanlawson/pouchdb-find#227]
It works with all other fields fine, but has no effect on _id.

```
localdb.find({
  selector: {
    _id: {$nin: ["list1", "list2"]}
  }
});
```
This still selects documents with the ids "list1" and "list2"

**Comment by greenimpala** [comment]
Does `regexp` work with _id also? http://plnkr.co/edit/wc4pb0B1Ly7NalaMmNMz?p=preview

This plnkr suggests otherwise :(

**Comment by garrensmith** [comment]
There is also a Mango issue related to this as well https://issues.apache.org/jira/browse/COUCHDB-3275

**Comment by garrensmith** [comment]
I can reproduce this issue. I will look to fix soon.

**Comment by garrensmith** [comment]
This should be fixed in the latest release. Could you verify for me and open this ticket again if it is not.
