### ISSUE TITLE
retrieve attachments with find 

### ISSUE THREAD

**Issue by vahidreza** [nolanlawson/pouchdb-find#232]
hi
how can I retrieve attachments with find plugin?
I have tried using attachments:true,  in the find options but no success.

**Comment by nolanlawson** [comment]
There isn't any way to do this currently in pouchdb-find; you would need to find the document ID and then do a separate `get()` or `getAttachment()` request. Looking at https://github.com/cloudant/mango it seems there is no explicitly-defined way to get documents or attachments, e.g. there is no `include_docs`.

Perhaps this would be a good opportunity to open an issue on CouchDB/Cloudant to support such a feature.

**Comment by garrensmith** [comment]
I'm closing this since its not an issue but a feature request. If you would like this feature the best approach is to send a mail to the CouchDB mailing list.
