### ISSUE TITLE
memory usage of find({}).sort()

### ISSUE THREAD

**Issue by chrischjh** [nolanlawson/pouchdb-find#236]
Hi there, for the leveldb backend, is the sorting being done in the node.js process memory? for example if I need to sort 5 million data, would it consume too much memory, like 500M or 1G? thanks

**Comment by garrensmith** [comment]
Sort will be done in memory. I'm not sure what kind of memory consumption will be used. But it would the same as sorting a large number of json objects. 

All misspelling thanks to my iPhone.




On Tue, Dec 20, 2016 at 11:21 AM +0200, "Chris Chen" <notifications@github.com> wrote:












Hi there, for the leveldb backend, is the sorting being done in the node.js process memory? for example if I need to sort 5 million data, would it consume too much memory, like 500M or 1G? thanks
