### ISSUE TITLE
find does not work with some unicode characters

### ISSUE THREAD

**Issue by 0x1mason** [nolanlawson/pouchdb-find#237]
Given doc
```js
{
  foo: 1,
  bar: "とう)京(きょう::\u0123\u0923\u0387;"
}
```
query `find({selector: { foo: 1, bar: "とう)京(きょう::\u0123\u0923\u0387;"}})` returns `[]`.

However, given doc
```js
{
  foo: 1,
  bar: "trucker's atlas"
}
```
query `find({selector: { foo: 1, bar: "trucker's atlas"}})` works as expected.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6257
