### ISSUE TITLE
Querying linked Documents?

### ISSUE THREAD

**Issue by wgrhstf** [nolanlawson/pouchdb-find#238]
I' quite new to NoSQL and so this ist maybe nonsense, but is ist possible to use pouchdb-find on linked documents?
In my CouchDB (which functions as master for a replicated PouchDB on the Client), there is a view to retrieve linked Documents. But I did not find a way to query this view, or query linked Documents directly via pouchdb-find.

**Comment by nolanlawson** [comment]
No, there is currently no such feature in pouchdb-find.

**Comment by wgrhstf** [comment]
Oh. I understand. So I'll find a workaround. But is this something on the roadmap for future releases? 
If pouchdb-find is going to replace map/reduce retrieving linked documents would be quite crucial.

**Comment by garrensmith** [comment]
It is something we thinking about. PouchDB-find follows CouchDB Mango. So it will have to be implemented there first.
