### ISSUE TITLE
Custom sort apart from ascending descending

### ISSUE THREAD

**Issue by RonCan** [nolanlawson/pouchdb-find#239]
I want to sort the results of couchdb query a.k.a mango queries based on custom sort. I need custom sort because if `Status` can be one of the following:

1. Active = 1
2. Sold = 2
3. Contingent = 4
4. Pending = 3

I want to sort the results on `Status` but not in an alphabetical order, rather my own weightage I assign to each value which can be seen in the above list. Here's the selector for `Status` query I'm using:

    {type:"Property", Status:{"$or":[{$eq: "Pending"}, {$eq:"Active"}, {$eq: "Sold"}]}}

If I use the `sort` array in my json with Status I think it'll sort alphabetically which I don't want.

I'm using Cloudant, which is based on CouchDB 2.0

**Comment by RonCan** [comment]
@nolanlawson This needs your kind attention

**Comment by nolanlawson** [comment]
Unfortunately if you want to do a custom sorting in the way you describe, you would need to read the entire database in-memory (e.g. with `allDocs()`) and do the sorting in JavaScript. Sorry about that!
