### ISSUE TITLE
Proposal: Computed Indices

### ISSUE THREAD

**Issue by NNemec** [nolanlawson/pouchdb-find#242]
Though pouchdb offers user friendly access to powerful functionality, it is fundamentally limited compared to map/reduce (see https://github.com/nolanlawson/pouchdb-find/issues/21#issuecomment-91207774). Even with adding more and more features to the selector, this will still leave the computational load in the find routine rather than shifting it into the indexing where it could be performed once and allow highly efficient queries like they can be performed with map/reduce.

I propose the introducion of "computed indices", which will allow most - if not all - of the performance of map/reduce as a clean and elegant extension of the existing pouchdb-find concept:

+Proposal:+
The db.createIndex function could have an optional argument 'map' of type 'function(doc)' that processes each document and returns a list of values that should be placed into the index. The 'fields' argument would in this case not refer to actually existing fields, but instead to "virtual" fields available for use in the find selector just like regular indexed fields.

+Notes:+
* I am not quite sure how the plural form "fields" should be adjusted. Even now, it is not clear to me what the difference is between one index with multiple fields and multiple indices...
* instead of a function returning values, one could also use the 'emit' function call syntax as in map/reduce. This is mostly a matter of taste.

With this straightforward extension, one could do complex combination of fields and costly computations at indexing time while greatly reducing the complexity and cost of the selection process.

**Comment by nolanlawson** [comment]
I think your analysis is fairly correct but the goal of `pouchdb-find` is to just copy exactly what the Cloudant/CouchDB Mango query language provides. For computed indexes I think the stance of Cloudant/CouchDB folks is that precomputed fields should be added directly to the document so that you can then index them directly. I agree it's not a perfect solution, though.

For all other cases map/reduce is still supported and will be indefinitely supported. :)

**Comment by NNemec** [comment]
Pre-computed fields are not an alternative to a powerful indexing mechanism. They do not offer any internal consistency guarantee, which is one of essential features of a database system.

From the pouchdb-find intro page, it sounds like map/reduce is kept only for legacy reasons but considered deprecated. Without a more powerful indexing mechanism, I would rather call pouch-find the comfortable entry-level solution and map/reduce the full-featured expert solution.

Personally, I find it rather diappointing to be able to start with the comfortable solution and then have to re-learn a very different syntax when I reach more advanced use-cases. Specifically, I have started pouchdb-live-find, which offers exactly the features I need. Now I need to rewrite lots of code to use map/reduce instead.

Are the Cloudant developers open to suggestions? Do you have an idea where to bring up this kind of suggestion? Is there any place where the pre-computed field solution has been discussed?

**Comment by garrensmith** [comment]
Hi @NNemec, the best way to bring up this idea is on the [CouchDB dev mailing list](http://couchdb.apache.org/) - scroll down to the mailing list section. 

Your proposal feels a lot like just using Map/Reduce. But I do agree PouchDB-Find/Mango is a bit limited at the moment. We do need to add more functionality. The best way to do that is through the CouchDB mailing list.

I'm going to close this PR.

**Comment by NNemec** [comment]
After an encouragement from the mailing list, I just created https://issues.apache.org/jira/browse/COUCHDB-3280
