### ISSUE TITLE
This query is extremely slow on mobile, ~10 seconds

### ISSUE THREAD

**Issue by Chozzle** [nolanlawson/pouchdb-find#243]
Should I expect this length of time? I have a database of about 1000 words. I'm not getting any warnings about missing indexes, I think they are correct. I'm using the cordova-sqlite adapter as I'm using a pre-built database.
var mSelector = {
            type: 'word',
            inWordLists: {
              $in: [wordListId]
            },
            _id: {
              $nin: reviewCardsIds
            }
          }

**Comment by Chozzle** [comment]
So I removed the cordova-sqlite adapter option and it now takes approximately 0.1 seconds. Thats an insane difference.

**Comment by garrensmith** [comment]
Thanks, that is interesting. 

All misspelling thanks to my iPhone.




On Sat, Jan 21, 2017 at 4:47 AM +0200, "Chozzle" <notifications@github.com> wrote:












So I removed the cordova-sqlite adapter option and it now takes approximately 0.1 seconds. Thats an insane difference.

**Comment by garrensmith** [comment]
Have you tried using this adapter https://github.com/nolanlawson/cordova-plugin-sqlite-2.
I'm closing this issue since it is not related to pouchdb-find.

**Comment by Chozzle** [comment]
Yes that is the adapter I'm using. I followed Nolan's guide on prebuilt pouchdb in Cordova. Actually I've noticed that using no index at all is even faster. It's down to a solid 0.1 seconds now, even though it gives me the warning.

**Comment by garrensmith** [comment]
Yes that probably makes sense. Using the _all_docs index could be faster as we not actually reading from disk for the other indexes but rather doing a map-reduce in memory for the query. This will hopefully change in the future.

**Comment by Chozzle** [comment]
Just to give an update, I changed my query to avoid the $nin selector and am using a standard prebuilt map query instead. I still have major problems with the sqlite adapter. With 6000 docs in the dB it really struggles. Constant 15 to 20% CPU usage and sometimes a query just fails to return the promise. Without the adapter it works fine
