### ISSUE TITLE
$exists should work with index

### ISSUE THREAD

**Issue by NNemec** [nolanlawson/pouchdb-find#244]
I was surprised to find that $exists does not work with indices.

For a field that is available only on a small set of documents, using an index to finding these documents quickly makes perfect sense.

Technically, this should not be a problem, since e.g. {$gte: ""} would do the same job for string fields.

**Comment by garrensmith** [comment]
There is an open ticket in Mango for this https://issues.apache.org/jira/browse/COUCHDB-2926

**Comment by NNemec** [comment]
Just realized now: Though $exists:true could be handled by index, a $exists:false does not work like this. Not sure whether this would be argument against this.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6256
