### ISSUE TITLE
find/filter in allDocs result

### ISSUE THREAD

**Issue by lgodard** [nolanlawson/pouchdb-find#247]
Hi,
First thanks a lot for all pouchDB
after some successfull use, i go deeper regarding performances and faces some problem on filtering

I built my base as recommanded regarding IDs 
(Use and abuse your doc IDs https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html)
--> a great advice as it is fast querying and covers most of my cases

But, sometime, i need to filter these results regarding a property of the contained doc.

Using allDocs, then filter the result in my js works but becomes slow when database grows, especially for top_level keys.

Using secondary index does not benefit from primary startkey/endkey result. It returns all the docs according the filtered index.

My question : what is the better solution ? use a secondary index ? but can i then benefit of a first filtering with allDocs ? Is there a way to combine primary and secondary index searches ?

Use case example
```
docs = {
{_id: "a_1", type: "t1"},
{_id: "a_2", type: "t1"},
{_id: "a_1_b_2_c_3", type: "t2"},
{_id: "a_1_b_2_c_4", type: "t2"},
{_id: "a_2_b_5_c_6", type: "t3"},
{_id: "a_2_b_5_c_7", type: "t3"},
{_id: "a_1_b_2", type: "t4"},
{_id: "a_2_b_5", type: "t4"}
}
```
looking for all docs with `_id` starting with `a` and with `type: t1`

Is something like this do-able ? any other suggestion welcomed

```
let options = {};
options.startkey = 'a_';
options.endkey = 'a_\uffff';
options.magic_filter = ... to be defined ... that checks type==='t1'
options.include_docs: true;
options.conflicts: true;

result = pouchdb.allDocs(options);

-->

{_id: "a_1", type: "t1", ...},
{_id: "a_2", type: "t1", ...}

```

**Comment by nolanlawson** [comment]
If I were you I would maybe use `find()` to find all docs of a certain type, and then filter in-memory.

The best way to think of this is to imagine which ordering (type then id vs id then type) will result in the smallest possible slice of your database, and then use that ordering. You could also do:

```
find({
  type: 't2',
  _id: {$gt: 'a_', $lt: 'a_\uffff'}
})
```

and let pouchdb-find do the rest. But I admit I'm not sure which index it will use; you'll need to test.

**Comment by lgodard** [comment]
Hi Nolan,

thanks a lot for your response.

You perfectly spotted the main problem requiring the smallest possible slice after first filtering. I'm actually calculating this in many of my uses cases. Results seems to be 'it depends' :-). Thanks a lot for focusing on this metric

Btw, some questions

- is there any overhead estimation querying a secondary index versus the primary on `_id`

- idea regarding primary index
due to particularity of my `_id` keys, the type can be deduced from the `_id`,
simplifying the use case presentation can lead to something like

```
docs = {
{_id: "a_1", type: "a"},
{_id: "a_2", type: "a"},
{_id: "a_1_b_2_c_3", type: "c"},
{_id: "a_1_b_2_c_4", type: "c"},
{_id: "a_2_b_5_c_6", type: "c"},
{_id: "a_2_b_5_c_7", type: "c"},
{_id: "a_1_b_2", type: "b"},
{_id: "a_2_b_5", type: "b"}
}
```
if i consider `allDocs`, with `startkey` and `endkey`, we are not in fact so far from the result

the `startkey` is `a_`
if `endkey` is `a_\uffff` --> i'll get all the docs

is there any strategy that would lead to express endkey as 
`a_ + other characters until '_'`

Thanks again for your response

Laurent

**Comment by lgodard** [comment]
Hi Nolan,
FYI, i tested a `_design/my_filter` (with a `map: function on doc.t`) and it improves things on root keys as `a_`. That was my primary need
I'll test with `pouchdb-find`
I'm still interested in any possibility manipulating primary keys

Thanks again for your advices ... and pouchdb :)
