### ISSUE TITLE
Dealing with different shapes

### ISSUE THREAD

**Issue by BigBlueHat** [nolanlawson/pouchdb-find#248]
I'm attempting to use pouchdb-find in my [page-notes](http://github.com/bigbluehat/page-notes) project. I can't (afaik) use Map/Reduce due to it's use of `eval()` and/or `new Function()`. However, I'm mostly getting "misses" when indexing the ever flexible world of JSON-LD documents.

Page Notes uses Web Annotation Data Model documents--which are JSON-LD documents (typically). The specific situation is that the values of `target` and `body` keys can be strings, arrays, or objects.

Specifically, I'm trying to generate a list of targeted Web Resources which can be stored in any of these spots:

```json
{"target": "http://example.com/"}
```

```json
{
  "target": {
    "source": "http://example.com/",
    "selector: {}
  }
}
```

```json
{
  "target": [
    {
      "source": "http://example.com/",
      "selector": {}
    },
    "http://example.org/"
  ]
}
```

I could attempt to normalize all inbound annotations into the array-based variation before indexing (upon storage), but I'd prefer to keep any inbound annotations in their original shape--so I can ship them back the way they came.

Thoughts?

/cc @tilgovi @treora

**Comment by nolanlawson** [comment]
Unfortunately if you need to do transformations on your documents before inserting into the index, then you will need to use map/reduce (and eval()) rather than pouchdb-find. 

There was a proposal recently on the mailing list for "computed indexes" in Mango; would this cover your use case? https://mail-archives.apache.org/mod_mbox/couchdb-dev/201701.mbox/browser

**Comment by BigBlueHat** [comment]
Thanks @nolanlawson! Looks like there's a related issue now: https://issues.apache.org/jira/browse/COUCHDB-3280

However, I'm not sure that would address it. It's mostly a case of the limitations of the `fields` property values when creating indexes (as well as how the resulting indexes work.

For instance, right now I'm just indexing `target`: https://github.com/BigBlueHat/page-notes/blob/master/src/storage.js#L8

If I index only `target` then (obviously) situations where target is a string "hit the index" when finding. However the `target.source` requests don't (again...probably obviously).

If, on the other hand, I try and index with both `target` and `target.source` in a single index, then whichever is first in the fields list is the one that gets hit: `fields: ["target", "target.source"]` or `fields: ["target.source", "target"]`

Lastly, if I create two separate indexes, then (of course) the individual indexes get hit as one would expect, but now there's two sets of results that would need combining. And `$and` just ain't gonna cut it there (for obvious reasons...).

...and all of that is only an attempt to deal with `target` and `target.source` (single object) and does not (yet) address `target[#].source` scenarios (which is next...).

What I'm (re)concluding is that dealing with JSON-LD (without Map/Reduce at least) is going to be easiest (and likely best) if indexed into something like [LevelGraph](http://levelgraph.io/)--[try the playground](https://github.com/WileyLabs/levelgraph-playground) if you want.

Probably it's (past) time for me to dig into writing an indexer for PouchDB... 😁

**Comment by BigBlueHat** [comment]
I'm going to close this one and see about submitting the issue upstream at CouchDB.

I've found that indexing both `target` and `target.source` works (hits the indexes) when searching for those specific selectors. However, searching for both of them together using `$or` doesn't hit the index--which is a separate issue I'll research/file.

The only thing I've not been able to sort (per this issue) is indexing inside of arrays. The `$in` operator does work for strings that might be in `target`, but does not work for object values (such as `source` inside the `target` array). That's the feature that I'll file with the CouchDB.

Thanks for listening. 😸
