### ISSUE TITLE
$lt and $gt is not working with limit

### ISSUE THREAD

**Issue by jkndrkn** [nolanlawson/pouchdb-find#250]
I am experiencing a perhaps related issue.

Here is my selector:

```
{
    "selector": {
        "_id": {
            "$gt": "surgery_case.",
            "$lt": "surgery_case.�"
        }
    }
}
```

I have a database with hundreds of records. 32 of these have an _id that starts with the "surgery_case." prefix. If I do not set a limit, the above query only returns 25 of these records.

If I do set a limit of, say, 35 the above query will return all 32 records.

NOTE: The special character at the end of the $lt clause is the character with code 0xffff.

**Comment by dholth** [comment]
Limit defaults to 25 if not set: http://docs.couchdb.org/en/2.0.0/api/database/find.html

**Comment by jkndrkn** [comment]
Thank you! Closing now.
