### ISSUE TITLE
search for text feilds with like operator

### ISSUE THREAD

**Issue by vahidreza** [nolanlawson/pouchdb-find#254]
@nolanlawson 
hi
i need to find docs based on some fields and i need the 'contains' or 'like' operator.
how can i achieve that with find plugin?

**Comment by unpete** [comment]
solution to your problem is `$regex`, see the [couchdb docs](http://docs.couchdb.org/en/2.0.0/api/database/find.html)

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6253
