### ISSUE TITLE
crytpo.createHash fallback to md5 (browser version) for ReactNative environment

### ISSUE THREAD

**Issue by copongcopong** [nolanlawson/pouchdb-find#255]
In ReactNative environment, pouchdb-find detects it is a Node.js environment, however, since ReactNative is just an "emulated" Node.JS, crytpo.createHash does not exist;

possible solution:

1. In ReactNative environment, set `process.browser = true;` before importing pouchdb-find;
2. feature detection for crypto.createHash in `exports.MD5` calls as seen on `/lib/utils.js` & `/lib/abstract-mapreduce/utils.js`

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6301

**Comment by nolanlawson** [comment]
pouchdb-find is moving to pouchdb/pouchdb, hence the issue move
