### ISSUE TITLE
Indexes created on mobiles are replicated on server

### ISSUE THREAD

**Issue by larryaubstore** [nolanlawson/pouchdb-find#258]
Hi, it it possible that indexes created on mobile devices are replicated on CouchDB server ? My database on CouchDB server is getting bigger. At the beginning, the database was taking 100M and now it goes to 16GB. 

Is it possible to create indexes on the mobile side only ?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6341

**Comment by nolanlawson** [comment]
This repo is defunct, please use the other repo :)
