### ISSUE TITLE
Regex with case insensitive not working

### ISSUE THREAD

**Issue by manikandan07081995** [nolanlawson/pouchdb-find#260]
"$regex" :  "(?i)mario.*" is working fine with couch DB mango query. But not working pouch DB find selector.kindly help me as soon as possible.

**Comment by unpete** [comment]
In our projects, we solve the problem by bringing the text to the lower case in a separate field and doing a search on it

**Comment by manikandan07081995** [comment]
@rdewolff  thank you for clarification. But I need search for an insensitive case then how can I do? Give me the better solution for search insensitive case.

**Comment by manikandan07081995** [comment]
@unpete  can u send the detail clarification to my mail id. **manikandan.kumaran@chainsys.com** this is my mail id.

**Comment by nolanlawson** [comment]
This repo is deprecated and has been moved into the main PouchDB repo. If this issue persists in the latest version of PouchDB, please file there: http://github.com/pouchdb/pouchdb/
