### ISSUE TITLE
Order of index fields matter when using sort

### ISSUE THREAD

**Issue by arnoutaertgeerts** [nolanlawson/pouchdb-find#27]
I noticed the following strange behavior while trying out the plugin and the `find()` method in combination with a `sort` option. 

The following code works:

```javascript
db.createIndex({
     index: ['date', 'type']
}).then(function() {
    return db.find({
        selector: {date: {$exists: true}, type: 'model'}
        sort: ['date']
    })
})
```

But when I change the order of the index (after deleting the previously created design doc) from `['date', 'type']` to `['type', 'date']`:

```javascript
db.createIndex({
     index: {fields: ['type', 'date']}
}).then(function() {
    return db.find({
        selector: {date: {$exists: true}, type: 'model'}
        sort: ['date']
    })
})
```

I get the following error message: `Error: couldn't find a usable index. try creating an index on: date, type`. 

Is there a reason why they should be ordere like this?

**Comment by nolanlawson** [comment]
Yep, this is by design. If you sort on `a`, then the index needs to be `a` or `a,b`, not `b,a`. Cloudant Query Language does this as well, so I'm just following their lead.

**Comment by arnoutaertgeerts** [comment]
ok, thanks!
