### ISSUE TITLE
http://nolanlawson.github.io/pouchdb-find/ is crashing at Chromium 39

### ISSUE THREAD

**Issue by fiatjaf** [nolanlawson/pouchdb-find#3]
It loads, shows an editor and then gives me a "Aw, Snap!"

**Comment by nolanlawson** [comment]
Cannot reproduce... did you try any other versions of Chrome?

**Comment by fiatjaf** [comment]
Works well on Chrome 37.

Well, don't bother, this computer is buggy anyway.

**Comment by nolanlawson** [comment]
OK, let's hope it was an isolated incident. :)
