### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for '$ne' in 123

### ISSUE THREAD

**Issue by cdaringe** [nolanlawson/pouchdb-find#30]
Hello:

in `pouchdb-find/lib/adapters/local/utils.js` in messageSelector

```js
function massageSelector(input) {
...
    if (typeof matcher === 'string') {
      matcher = {$eq: matcher};
    } else if ('$ne' in matcher && !wasAnded) {
...
}
```

I receive the above error.  matcher is an integer in this case, 123--and it barks.  Tips?  Thanks!

**Comment by nolanlawson** [comment]
Can you provide your code that caused the error?

**Comment by cdaringe** [comment]
```js
// debuggins.js
'use strict';

var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-find'));

var p = new PouchDB('./test');
p
    .post({a: 123})
    .then(function() {
        return p.find({selector: { a: 123 } });
    })
    .then(console.dir)
    .catch(console.dir);
```

**Comment by nolanlawson** [comment]
Oh yeah, my bad. That's a bad bug.

**Comment by nolanlawson** [comment]
fixed by b180b6fd904cc00b9ce9420d1cef33f827856766 and released in the latest version

**Comment by cdaringe** [comment]
:+1: !  when i first saw that `pouch.query` was moving to a plugin, I grumbled a bit, but in retrospect, i think this is a much cleaner interface!  much appreciated!

**Comment by nolanlawson** [comment]
glad ya like it :)
