### ISSUE TITLE
Multiple selectors

### ISSUE THREAD

**Issue by chrisschaub** [nolanlawson/pouchdb-find#32]
Is there a way to specify multiple selectors?

**Comment by nolanlawson** [comment]
You mean an ANDed query? Yes.

**Comment by nolanlawson** [comment]
Here are some examples: https://github.com/nolanlawson/pouchdb-find#examples

Let me know if that helps!

**Comment by chrisschaub** [comment]
Thanks!! Totally missed that.

On Wed, Apr 29, 2015 at 2:23 PM, Nolan Lawson <notifications@github.com>
wrote:

> Here are some examples:
> https://github.com/nolanlawson/pouchdb-find#examples
>
> Let me know if that helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolanlawson/pouchdb-find/issues/32#issuecomment-97550340>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by ivandroid** [comment]
Does the $and operator work on same fields? E.g. I would like to select docs having names 'Mario' and 'F-Zero'.

**Comment by ivandroid** [comment]
What abaout the $or operator? I would like to get documents with series 'Mario' or 'F-Zero'. How can I do this? Many thanks!

**Comment by ivandroid** [comment]
What about the $or operator? I would like to get documents with series 'Mario' or 'F-Zero'. How can I do this? Many thanks!
