### ISSUE TITLE
Non-contributors get test failures in Travis

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-find#35]
This is the weirdest bug. An example failure is [here](https://travis-ci.org/nolanlawson/pouchdb-find/jobs/61137867). The error I end up seeing is:

```
  1) http test suite 1 "before each" hook:
     Missing JSON list of 'docs'
```

I think this is the error you'd see if we only had access to CouchDB, not to Cloudant. So I guess the problem is that Travis can only use the "secure" vars if it's a collaborator submitting the PR? 

@daleharvey do you have any hunches about this?

**Comment by daleharvey** [comment]
Yeh thats exactly right, only contributors have access to secure vars (otherwise a random person can just echo $VAR) to expose them. We avoid running the tests that use secure vars in pouch

**Comment by nolanlawson** [comment]
Crap, I was worried about that. I guess the real solution will be to start building couch-master, now that mango is merged :stuck_out_tongue:

**Comment by garrensmith** [comment]
I think we can close this, since we testing against couchdb-master?

**Comment by nolanlawson** [comment]
yep, this is no longer an issue thanks to that :)
