### ISSUE TITLE
gh-pages uses old version

### ISSUE THREAD

**Issue by viskin** [nolanlawson/pouchdb-find#37]
Please merge master to gh-pages (uses 0.3.2), as latest version (0.3.4) seems to fix serious bugs.
I played with http://nolanlawson.github.io/pouchdb-find page, and run into bugs that
definitely weren't happening in code that I write. Took few minutes to understand that versions
are different, and 0.3.4 is much more stable.
Great stuff, btw.

**Comment by nolanlawson** [comment]
sorry, my bad. I'll update the gh-pages branch!
