### ISSUE TITLE
$or operator?

### ISSUE THREAD

**Issue by ivandroid** [nolanlawson/pouchdb-find#39]
What about the $or operator? I would like to get documents with series 'Mario' or 'F-Zero'. How can I do this? Many thanks!

P.S.: Maybe this functionality will be integrated in the coming $in operator. When can we expect this functionality?

**Comment by nolanlawson** [comment]
Not implemented yet. :) In the meantime you can run two separate queries.

**Comment by garrensmith** [comment]
Closing as $or is now in master.
