### ISSUE TITLE
Arrays and $eq

### ISSUE THREAD

**Issue by microadam** [nolanlawson/pouchdb-find#40]
Hello,

Should I be able to do something like the below?

I would expect a query like:

```
db.find({ category: 'fruit' })
```

to find a record which looks like:

```
{ _id: 1, category: [ 'fruit', 'veg' ] }
```

Should this work? Or am I supposed to do it another way? It doesn't throw any errors, so I am assuming it should work.

Thanks!

**Comment by nolanlawson** [comment]
That's the `$elemMatch` selector, which is not implemented yet.

**Comment by garrensmith** [comment]
v0.7.0 now has `$elemMatch` support. So I'm now closing this.
