### ISSUE TITLE
query vs find for reducing a data set

### ISSUE THREAD

**Issue by yattias** [nolanlawson/pouchdb-find#46]
Hi Nolan,

I recently stated using you plugin which is awesome.

In the docs you mention that ``pouch.query`` will be replaced with this plugin which leads me to the following question:

In pouchdb, it is possible to use design docs with indexes to efficiently reduce a data set as your wrote in [this post](http://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html). How would I accomplish the same thing with **pouchdb-find**? Is it/will it be possible to efficiently reduce a data set?

**More specifics**:
Suppose I have a db with many docs and each doc has a ``tags`` key. Tags in an array of strings.
How can I efficiently get all unique tags in the db?

**Thanks!**

**Comment by nolanlawson** [comment]
Your `tags` example will be possible to do efficiently in `pouchdb-find` using the `$elemMatch` matcher, but it hasn't been implemented yet. :( So you'll have to use `query()` for now.

**Comment by yattias** [comment]
:( :(

That's alright! Thanks.
I have a couple of months before I go to production so in the meantime I may not use indexes and check back on future releases.

**Comment by garrensmith** [comment]
v0.7.0 now has `$elemMatch` support. So I'm now closing this.

**Comment by garrensmith** [comment]
v0.7.0 now has `$elemMatch` support. So I'm now closing this.
