### ISSUE TITLE
'Refer header required'

### ISSUE THREAD

**Issue by roblav96** [nolanlawson/pouchdb-find#47]
{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }

I get that error after installing this plugin.

Tried updating node, puchdb, everything, etc. and still this error. Normal requests work fine.

**Comment by roblav96** [comment]
can anyone help?

im using express as a restful API. and a fresh install ubuntu 14.04 and couchdb 1.6.1

========================================
{ email: 'lol@gmx.com',
  password: 'cumonnow',
  _id: 'lol' }
  pouchdb:api http://admin:admin@localhost:5984/report_users +1ms request { method: 'POST',
  url: '_find',
  body: 
   { selector: { email: 'lol@gmx.com' },
     fields: [ '_id', 'email' ] } }
PUT /register 200 17.804 ms - 4
  pouchdb:api http://admin:admin@localhost:5984/report_users +8ms request error { [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }
========================================
{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }

**Comment by roblav96** [comment]
It seems as though I can't save/create a design doc with node-cradle either.

Is there a way to inject a dummy referer header into every request somehow? Someone please help :(

**Comment by nolanlawson** [comment]
This plugin does not work with CouchDB, only with Cloudant. If you try it against CouchDB you will see a weird error about "referer header required."
