### ISSUE TITLE
LocalStorage makes multiple indexes

### ISSUE THREAD

**Issue by darkyen** [nolanlawson/pouchdb-find#48]
.createIndex always creates a new index when using localstorage on chrome, never returns the exists state.
(for some reason it has 168 indices with google chrome)

**Comment by nolanlawson** [comment]
Ah yeah, I don't think I dedup unless you pass in a name. Good bug.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6287
