### ISSUE TITLE
find api and attachments

### ISSUE THREAD

**Issue by JDqv** [nolanlawson/pouchdb-find#49]
Is there any way to retrieve find results with attachments included?
Its not even clear for me how and if cloundant API does that.

**Comment by nolanlawson** [comment]
That's a very good question. I think the answer might, disappointingly, be no. If so, though, that is a really annoying limitation.

For the record, though, you can still use `getAttachment` like you normally would, and it's actually just as efficient as it would be if I added the functionality to this plugin somehow. It's just more code for you to have to write, which is a bummer.

**Comment by nolanlawson** [comment]
@rnewson @kocolosk Are there any plans to add an `attachments=true` to the Mango API?

**Comment by garrensmith** [comment]
I'm closing this, since I don't think its in the roadmap for now.
