### ISSUE TITLE
README.md - creating index as adviced results in an error

### ISSUE THREAD

**Issue by mikkokam** [nolanlawson/pouchdb-find#5]
Probably missing top level object **index** ?

Is:

    db.createIndex({
      name: 'myindex',
      fields: ['foo', 'bar'],
      type: 'json'
    }).then(function (result) {

Maybe should be something like this?

    db.createIndex({
        index: {
            name: 'myindex',
            fields: ['foo', 'bar'],
            type: 'json'
        }
    }).then(function () {

**Comment by nolanlawson** [comment]
yup, readme bug

**Comment by nolanlawson** [comment]
fixed, thanks!
