### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by viskin** [nolanlawson/pouchdb-find#51]
Please add explanation to README for usage with AMD (requirejs).
If AMD is currently not supported, if would be nice to add support for it.

**Comment by nolanlawson** [comment]
Yeah, I've made a point of not supporting AMD for all my pouchdb plugins because it would simply be too much work. There are instructions for AMDifying here, and I would accept a PR on the README! :)

https://github.com/nolanlawson/pouchdb-all-dbs/issues/12#issuecomment-64114074

**Comment by viskin** [comment]
I [forked the pouchdb-find](https://github.com/viskin/pouchdb-find/tree/amd-support) and modified the build there with *browserify --standalone*.
I registered the branch with bower, so everyone interested in AMD version of pouchdb-find can use:

      bower install pouchdb-find-amd#amd-support

FYI
