### ISSUE TITLE
Multi-field sort doesn't work for mixed asc/desc

### ISSUE THREAD

**Issue by bendavis78** [nolanlawson/pouchdb-find#56]
Then given example should sort by series ascending, and within each series should sort by debut year descending. Instead, debut year is ascending.
```javascript
db.createIndex({index: {fields: ['series', 'debut']}}).then(function() {
  return db.find({
    selector: {_id: {$gt: 'a'}, series: {$exists: true}, debut: {$exists: true}},
    sort: [{series: 'asc'}, {debut: 'desc'}]
  });
});
```

**Comment by nolanlawson** [comment]
Whoops, mistake on my part! I will try to fix soon.

**Comment by garrensmith** [comment]
@bendavis78 and @nolanlawson That sort isn't actually possible for Cloudant Query and CouchDB Mango. If you try and run that query on Cloudant or CouchDB master branch you get
`Sorts currently only support a single direction for all fields.`

I'm closing since this is not possible at this stage.
