### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by tomaszliptak** [nolanlawson/pouchdb-find#61]
Do you have any roadmap? 
Any date for final release?
Any plans for releasing at least those operators: $in, $or, $not, $elemMatch?
What's the plan for other operators?

**Comment by nolanlawson** [comment]
No roadmap, because this is a hobby project for me and nobody pays me for it. :) But pull requests are always welcome.

**Comment by nolanlawson** [comment]
sorry, no roadmap planned
