### ISSUE TITLE
Couch master started failing in Travis

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-find#62]
> ERROR: OTP release R14B04 does not match required regex R16B03-1|17|18

cc @garrensmith. Not sure what changed since your PR was written...

**Comment by garrensmith** [comment]
I'll take a look and see why.

**Comment by garrensmith** [comment]
@nolanlawson This is fixed in #63

**Comment by nolanlawson** [comment]
c7d60d23ac69ce117bb7dda265436965b63177c8
