### ISSUE TITLE
Query _all_docs index fails with phantomjs/websql

### ISSUE THREAD

**Issue by garrensmith** [nolanlawson/pouchdb-find#66]
If I create a selector like this

`
db.find({
  selector: {
   _id: {
         $gt: null
    }
}
});
`

This will return all the docs in the database. It works on Node.js, Firefox and Chrome. But fails with Phantomjs and websql.

**Comment by nolanlawson** [comment]
Weird, wonder if it's a Phantom thing or a WebSQL thing? We could test Safari or Chrome+WebSQL to try to figure out.

**Comment by nolanlawson** [comment]
fixed: 12ecc0e697d8be57c983c1a63783f7b434010d20

**Comment by nolanlawson** [comment]
whoops, not actually fixed

**Comment by nolanlawson** [comment]
OK, actually found a fix. For what it's worth, you can also test this in Safari.

**Comment by nolanlawson** [comment]
e1ca2e2d18041f05a3d19bce4254f4d7b349ad20
