### ISSUE TITLE
$exists tests are incorrect

### ISSUE THREAD

**Issue by garrensmith** [nolanlawson/pouchdb-find#67]
`$exists` is an in memory filter. Instead of querying like this `selector: {'foo': {'$exists': true}},`.
We actually need to declare an index as well so it needs to be something like this
`selector: {_id" : {"$gt" : null}, 'foo': {'$exists': true}},`.

This is the reason why the Cloudant/CouchDB tests fail.

**Comment by nolanlawson** [comment]
Yeah, I can't remember why I implemented that differently. :/ Definitely worth fixing.

**Comment by garrensmith** [comment]
Cool. I'll take a look at this next week.
