### ISSUE TITLE
Creating index with custom name or ddoc still creates random names

### ISSUE THREAD

**Issue by Sturgelose** [nolanlawson/pouchdb-find#73]
I'm creating indexes with custom names in order to track if they have to be updated or not.
However, in the response, I still get a random index name and random ddoc.

I'm creating indexes such as:
```
var success = function (result) {
        $log.log('INFO: PouchDB index "section.type.date"', result.result);
      }

      var error = function (err) {
        $log.log(err);
      }

      db.createIndex({
        index: {
          fields: ['sectionId', 'contentType', 'date'],
          name: 'contentList',
          ddoc: 'contentList'
        }
      }).then(success).catch(error);

      db.createIndex({
        index: {
          fields: ['sectionId', 'countryId'],
          name: 'sectionList',
          ddoc: 'sectionList'
        }
      }).then(success).catch(error);
```

And I get a response in the success where result variable is such as:
```
id: "_design/idx-16802bfc8dace8aa27c3f0efb60e59c3"
name: "idx-16802bfc8dace8aa27c3f0efb60e59c3"
result: "exists"
```

I'll try to take a look at the code to see if I can find the issue!

**Comment by garrensmith** [comment]
@Sturgelose thats for reporting. Let me know if you need help looking in the code to find the issue. It would be great if you could fix this for us. I'm happy to help you do that.

**Comment by nolanlawson** [comment]
fixed
