### ISSUE TITLE
$and or a problem with index

### ISSUE THREAD

**Issue by finchen** [nolanlawson/pouchdb-find#75]
Hi.

Thank you for the great plugin.

I have not been able to debug properly yet but maybe you could help.
I have a case working perfectly fine on the browser but not on an android 5 phone.

My document are simple
```
{
 _id: '123',
  type: 'type1',
  category: 'category1',
  name: 'My Name'
}
```
`category` can be null

and the index
```
db.createIndex({
				  index: {
				    fields: ['type', 'category']
				  }
				})
```

the query (1) works fine in chrome
```
db.find({
		  selector: {
		    $and: [
		    	{ type: 'type1' },
		    	{ category: 'category1' }
			]
		  }	
		});
```

or  query (2)
```
db.find({
		  selector: {
		    	 type: 'type1' ,
		  }	
		});
```

a query (3) on the wrong index and there is an error: index does not exist (normal)
```
db.find({
		  selector: {
		    	category: 'category1' 
		  }	
		});
```

on android 5 (built with ionic and so running in webview)
(1) returns no result..
(2) returns 25 documents out of 93
(3) return a promise but no callback, no error ..

I tried to add an index on `category` only (or even other fields - `name` never null) and query only that field and it does not return any result

I will keep looking tomorrow and might give more detail.
If you need anything, let me know

**Comment by garrensmith** [comment]
Hi @finchen, thanks for the comprehensive error report. 

@nolanlawson any idea how we can debug this? I don't know anything about debugging on mobile phones.

**Comment by nolanlawson** [comment]
@garrensmith If you have an Android phone, you can plug it in to your USB drive and then in Chrome go to `chrome://inspect`; there are instructions here: https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging

Else you will need to start up an Android emulator, for which the steps are similar.

**Comment by nolanlawson** [comment]
@finchen Which adapter are you using? IndexedDB, WebSQL, SQLite plugin...? Also if you could write a small web page or script to reproduce, it would be fantastic.

**Comment by finchen** [comment]
WebSQL on chrome and SQLlite on android.
It is working fine by removing the sqllite plugin.
Not sure if good or bad news..
At the time I did not see the warning about the sqllite plugin on the pouchdb adapaters documentation page.. I am a bit worry to have based a couple of apps on a 80mb simple database with attachment in it (I know it's not ideal, but since it is supported it is so easy.. and great)

this is the extra log info (in chrome://inspect) I get when on android
```
OPEN database: _pouch_mydb-mrview-b878448f9d3d65c0f259c27a219cade9
new transaction is waiting for open operation
DB opened: _pouch_mydb-mrview-b878448f9d3d65c0f259c27a219cade9 
```

To reproduce, you'll need a cordova app with websql
```
npm install -g cordova
cordova create testapp com.testapp Testapp
cd testapp
cordova platforms add android
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.console
cordova plugin add org.apache.cordova.device
cordova plugin add cordova-sqlite-storage
cordova run android
```

once loaded you can run these blocks one by one from `chrome://inspect`
```javascript

var script = document.createElement('script');
script.src = "//cdn.jsdelivr.net/pouchdb/5.0.0/pouchdb.min.js";
document.head.appendChild(script);

script = document.createElement('script');
script.src = "https://raw.githubusercontent.com/nolanlawson/pouchdb-find/master/dist/pouchdb.find.js";
document.head.appendChild(script);

var db = new PouchDB('test', {adapter: 'websql'});
db.put({
  _id: 'mydoc',
  type: 'type1',
  category: 'category1',
  title: 'Heroes'
});

db.createIndex({
		  index: {
		    fields: ['type', 'category']
		  }
		}); 

db.find({
		  selector: {
		    $and: [
		    	{ type: 'type1' },
		    	{ category: 'category1'} 
			]
		  }	
		}).then(function(result){

			console.log('expect 1 result but get 0', result);
});
```

**Comment by nolanlawson** [comment]
That is good news. We are aware that the SQLite Plugin has *tons* of issues mostly due to a buggy implementation, so we don't recommend it anymore. Especially on Android, your code will be both faster and more reliable if you use IndexedDB or WebSQL (take your pick; they're both good on Android).
