### ISSUE TITLE
EventEmitter memory leak detected error

### ISSUE THREAD

**Issue by martinwoitzik** [nolanlawson/pouchdb-find#76]
Hi there,

when adding more than 11 keys to get indexed I always get the following error in the console and thus the building of indexes also seem to be cancelled:

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Is there a quick-fix that could solve this problem? Don't know if increasing the setMaxListeners limit as suggested is a good idea?!

**Comment by nolanlawson** [comment]
Increasing the maxListeners is typicaly fine, but it would be nice to know what you're doing just in case there is a deeper issue here? Are you creating/destroying lots of databases, or creating lots of indexes, or something else...?

**Comment by martinwoitzik** [comment]
I am creating four databases, each with multiple indexes to allow fast search-queries. Where do I have to put the maxListeners setting in the code?

**Comment by nolanlawson** [comment]
Most likely on the `PouchDB` constructor itself, else the DB. If you're not sure, use https://github.com/nolanlawson/throw-max-listeners-error to find where the error is being thrown. Also check out this: http://pouchdb.com/errors.html#event_emitter_limit

**Comment by martinwoitzik** [comment]
Thanks! That did the trick... :)
