### ISSUE TITLE
Move pouchdb-find to the pouchdb org

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-find#79]
I think with the custom builds and @garrensmith's recent fixes, we are increasingly reaching a point where

1. we will release pouchb-find 1.0, and 
2. we will include pouchdb-find in pouch core, as a replacement for mapreduce.

To start with, I would like to move this module from `github.com/nolanlawson` to `github.com/pouchdb` and promote @garrensmith to a PouchDB core contributor. Any objections?

/cc @daleharvey @nickcolley @marten-de-vries @calvinmetcalf

**Comment by nolanlawson** [comment]
FWIW this weekend I am pretty serious about fixing pouchb-find bugs and increasing test coverage to 100% instead of messing around with other weird plugins

**Comment by daleharvey** [comment]
Nope those all sounds awesome, thanks so much @garrensmith (kinda thought you were already a committer)

**Comment by marten-de-vries** [comment]
Sounds great! :)

I'd have preferred to have no query module at all in PouchDB, but with the custom build work that becomes a non-issue: I'm fine with including pouchdb-find as the default.

**Comment by nickcolley** [comment]
I'm +1 for this, @garrensmith defintely should be a core contributor!

Just a few thoughts in terms of the documentation.

How do we deprecate map/reduce without making it hard for people maintaining older code.

I presume we'll want to keep map/reduce documentation to a minimum promoting find, do we need to version the docs?

**Comment by nolanlawson** [comment]
@nickcolley Very good question. I think maybe the docs need an overhaul, and as for the docs, I feel like they should all be in one place.

As for mapreduce itself, maybe we should move it back into a separate repo? Or move pouchdb-find into pouch core? Really not sure what the best path is here, since the custom builds make it so trivial for users to include "plugins" that are actually part of PouchDB's repo.

**Comment by nickcolley** [comment]
I think if we moved map/reduce into a space where it's considered a plugin we can put the documentation alongside it. So i'd be for that approach, since it'd be easy to find the docs you need and we wouldnt need to version the core docs.

**Comment by garrensmith** [comment]
Thanks all for the support, I appreciate it.

I think moving Pouchdb-find into core is a great idea since its a lot easier to understand, specially for beginners. But I do think we need to state when map/reduce would be a better fit. 

I'm new to the documentation side of PouchDB. But could we have a plugin's section in the documentation with some of the official supported plugins listed there. We could then include the map/reduce docs there.

**Comment by garrensmith** [comment]
A quick update on this. I've made some fixes and I think we are ready to do a release candidate for v1 at least. We now support all functionality. I think there might be a few small bugs. So I'll do a bit more testing. 

When would you like to move this to the pouchdb repo? And when do we do a pouchdb release with this?

**Comment by nolanlawson** [comment]
@garrensmith I think the big blocker to releasing this as part of PouchDB is the CouchDB 1.7/2.0 release. I've seen a *lot* of user confusion about trying to use pouchdb-find with 1.6 and failing.

Another blocker in my opinion is https://github.com/pouchdb/pouchdb/issues/4449, i.e. exposing some way for users to selectively exclude map/reduce or pouchdb-find. Otherwise all we can do is bloat PouchDB's core size by adding *both* pouchdb-find and mapreduce. (Or I guess we could do a breaking change where neither is included by default, but I feel like the default should be to include as much as possible, so that people can quickly get up and running, and then trim down the size later as needed.)

**Comment by nolanlawson** [comment]
tracking in https://github.com/pouchdb/pouchdb/issues/5192
